const unit07 = [
    {"en": "accident", "ru": "несчастный случай", "part_of_speech": "n", "pronunciation": "/ˈæksɪdənt/"},
    {"en": "air", "ru": "воздух", "part_of_speech": "n", "pronunciation": "/eə(r)/"},
    {"en": "altitude", "ru": "высота", "part_of_speech": "n", "pronunciation": "/ˈæltɪtjuːd/"},
    {"en": "arthritis", "ru": "артрит", "part_of_speech": "n", "pronunciation": "/ɑːˈθraɪtɪs/"},
    {"en": "astronaut", "ru": "космонавт", "part_of_speech": "n", "pronunciation": "/ˈæstrənɔːt/"},
    {"en": "at", "ru": "в", "part_of_speech": "prep", "pronunciation": "/æt/"},
    {"en": "aviation", "ru": "авиация", "part_of_speech": "n", "pronunciation": "/ˌeɪviˈeɪʃn/"},
    {"en": "badly", "ru": "плохо", "part_of_speech": "adv", "pronunciation": "/ˈbædli/"},
    {"en": "because", "ru": "потому что", "part_of_speech": "conj", "pronunciation": "/bɪˈkɒz/"},
    {"en": "cake", "ru": "пирог", "part_of_speech": "n", "pronunciation": "/keɪk/"},
    {"en": "carefully", "ru": "внимательно", "part_of_speech": "adv", "pronunciation": "/ˈkeəfəli/"},
    {"en": "channels", "ru": "каналы", "part_of_speech": "pl n", "pronunciation": "/ˈtʃænlz/"},
    {"en": "collect", "ru": "собирать", "part_of_speech": "v", "pronunciation": "/kəˈlekt/"},
    {"en": "college", "ru": "колледж", "part_of_speech": "n", "pronunciation": "/ˈkɒlɪdʒ/"},
    {"en": "comics", "ru": "комиксы", "part_of_speech": "pl n", "pronunciation": "/ˈkɒmɪks/"},
    {"en": "compass", "ru": "компас", "part_of_speech": "n", "pronunciation": "/ˈkʌmpəs/"},
    {"en": "complete", "ru": "завершать", "part_of_speech": "v", "pronunciation": "/kəmˈpliːt/"},
    {"en": "congratulations", "ru": "поздравления", "part_of_speech": "pl n", "pronunciation": "/kənˌɡrætʃuˈleɪʃnz/"},
    {"en": "crash", "ru": "разбивать", "part_of_speech": "v", "pronunciation": "/kræʃ/"},
    {"en": "crossing", "ru": "пересечение", "part_of_speech": "n", "pronunciation": "/ˈkrɒsɪŋ/"},
    {"en": "dangerous", "ru": "опасный", "part_of_speech": "adj", "pronunciation": "/ˈdeɪndʒərəs/"},
    {"en": "deeply", "ru": "глубоко", "part_of_speech": "adv", "pronunciation": "/ˈdiːpli/"},
    {"en": "dishwasher", "ru": "посудомоечная машина", "part_of_speech": "n", "pronunciation": "/ˈdɪʃwɒʃə/"},
    {"en": "education", "ru": "образование", "part_of_speech": "n", "pronunciation": "/ˌedʒuˈkeɪʃn/"},
    {"en": "enormous", "ru": "огромный", "part_of_speech": "adj", "pronunciation": "/ɪˈnɔːməs/"},
    {"en": "equipment", "ru": "оборудование", "part_of_speech": "n", "pronunciation": "/ɪˈkwɪpmənt/"},
    {"en": "events", "ru": "события", "part_of_speech": "pl n", "pronunciation": "/ɪˈvents/"},
    {"en": "exploration", "ru": "исследование", "part_of_speech": "n", "pronunciation": "/ˌekspləˈreɪʃn/"},
    {"en": "fast food", "ru": "фастфуд", "part_of_speech": "n", "pronunciation": "/ˌfɑːst ˈfuːd/"},
    {"en": "finally", "ru": "наконец, окончательно", "part_of_speech": "adv", "pronunciation": "/ˈfaɪnəli/"},
    {"en": "fireworks", "ru": "фейерверки", "part_of_speech": "pl n", "pronunciation": "/ˈfaɪəwɜːks/"},
    {"en": "flag", "ru": "флаг", "part_of_speech": "n", "pronunciation": "/flæɡ/"},
    {"en": "flight", "ru": "полет", "part_of_speech": "n", "pronunciation": "/flaɪt/"},
    {"en": "fluently", "ru": "бегло", "part_of_speech": "adv", "pronunciation": "/ˈfluːəntli/"},
    {"en": "fog", "ru": "туман", "part_of_speech": "n", "pronunciation": "/fɒɡ/"},
    {"en": "fortunately", "ru": "к счастью", "part_of_speech": "adv", "pronunciation": "/ˈfɔːtʃənətli/"},
    {"en": "giant", "ru": "огромный", "part_of_speech": "adj", "pronunciation": "/ˈdʒaɪənt/"},
    {"en": "habit", "ru": "привычка", "part_of_speech": "n", "pronunciation": "/ˈhæbɪt/"},
    {"en": "high school", "ru": "старшая школа", "part_of_speech": "n", "pronunciation": "/ˈhaɪ skuːl/"},
    {"en": "hits", "ru": "удары", "part_of_speech": "pl n", "pronunciation": "/hɪts/"},
    {"en": "hospital", "ru": "больница", "part_of_speech": "n", "pronunciation": "/ˈhɒspɪtl/"},
    {"en": "ill", "ru": "больной", "part_of_speech": "adj", "pronunciation": "/ɪl/"},
    {"en": "immediately", "ru": "немедленно", "part_of_speech": "adv", "pronunciation": "/ɪˈmiːdiətli/"},
    {"en": "impossible", "ru": "невозможный", "part_of_speech": "adj", "pronunciation": "/ɪmˈpɒsəbl/"},
    {"en": "injury", "ru": "травма", "part_of_speech": "n", "pronunciation": "/ˈɪndʒəri/"},
    {"en": "inscription", "ru": "надпись", "part_of_speech": "n", "pronunciation": "/ɪnˈskrɪpʃn/"},
    {"en": "invitation", "ru": "приглашение", "part_of_speech": "n", "pronunciation": "/ˌɪnvɪˈteɪʃn/"},
    {"en": "invite", "ru": "приглашать", "part_of_speech": "v", "pronunciation": "/ɪnˈvaɪt/"},
    {"en": "It sounds great!", "ru": "Звучит здорово!", "part_of_speech": "phrase", "pronunciation": "/ɪt saʊndz ɡreɪt/"},
    {"en": "join", "ru": "присоединяться", "part_of_speech": "v", "pronunciation": "/dʒɔɪn/"},
    {"en": "journey", "ru": "путешествие", "part_of_speech": "n", "pronunciation": "/ˈdʒɜːni/"},
    {"en": "know", "ru": "знать", "part_of_speech": "v", "pronunciation": "/nəʊ/"},
    {"en": "land", "ru": "приземляться", "part_of_speech": "v", "pronunciation": "/lænd/"},
    {"en": "leap", "ru": "прыгать, скакать", "part_of_speech": "v", "pronunciation": "/liːp/"},
    {"en": "life", "ru": "жизнь", "part_of_speech": "n", "pronunciation": "/laɪf/"},
    {"en": "lift off", "ru": "взлетать (на самолете)", "part_of_speech": "v", "pronunciation": "/ˈlɪft ɒf/"},
    {"en": "lunar module", "ru": "лунный модуль", "part_of_speech": "n", "pronunciation": "/ˈluːnə(r) ˈmɒdjuːl/"},
    {"en": "man", "ru": "мужчина", "part_of_speech": "n", "pronunciation": "/mæn/"},
    {"en": "mankind", "ru": "человечество", "part_of_speech": "n", "pronunciation": "/mænˈkaɪnd/"},
    {"en": "midnight", "ru": "полночь", "part_of_speech": "n", "pronunciation": "/ˈmɪdnaɪt/"},
    {"en": "modern", "ru": "современный", "part_of_speech": "adj", "pronunciation": "/ˈmɒdn/"},
    {"en": "moon", "ru": "луна", "part_of_speech": "n", "pronunciation": "/muːn/"},
    {"en": "movie", "ru": "фильм", "part_of_speech": "n", "pronunciation": "/ˈmuːvi/"},
    {"en": "no idea", "ru": "без понятия", "part_of_speech": "phrase", "pronunciation": "/nəʊ aɪˈdɪə/"},
    {"en": "non-stop", "ru": "без остановки", "part_of_speech": "adj", "pronunciation": "/ˌnɒn ˈstɒp/"},
    {"en": "on", "ru": "на", "part_of_speech": "prep", "pronunciation": "/ɒn/"},
    {"en": "passport", "ru": "паспорт", "part_of_speech": "n", "pronunciation": "/ˈpɑːspɔːt/"},
    {"en": "peace", "ru": "мир", "part_of_speech": "n", "pronunciation": "/piːs/"},
    {"en": "philosophy", "ru": "философия", "part_of_speech": "n", "pronunciation": "/fəˈlɒsəfi/"},
    {"en": "pioneer", "ru": "пионер, первооткрыватель", "part_of_speech": "n", "pronunciation": "/ˌpaɪəˈnɪə(r)/"},
    {"en": "planes", "ru": "самолеты", "part_of_speech": "pl n", "pronunciation": "/pleɪnz/"},
    {"en": "pocket money", "ru": "карманные деньги", "part_of_speech": "n", "pronunciation": "/ˈpɒkɪt mʌni/"},
    {"en": "prepare", "ru": "подготавливать", "part_of_speech": "v", "pronunciation": "/prɪˈpeə(r)/"},
    {"en": "professor", "ru": "профессор", "part_of_speech": "n", "pronunciation": "/prəˈfesə(r)/"},
    {"en": "psychology", "ru": "психология", "part_of_speech": "n", "pronunciation": "/saɪˈkɒlədʒi/"},
    {"en": "publish", "ru": "публиковать", "part_of_speech": "v", "pronunciation": "/ˈpʌblɪʃ/"},
    {"en": "put up", "ru": "выстовить, повесить", "part_of_speech": "v", "pronunciation": "/pʊt ˈʌp/"},
    {"en": "quickly", "ru": "быстро", "part_of_speech": "adv", "pronunciation": "/ˈkwɪkli/"},
    {"en": "quietly", "ru": "тихо", "part_of_speech": "adv", "pronunciation": "/ˈkwaɪətli/"},
    {"en": "relativity", "ru": "относительность", "part_of_speech": "n", "pronunciation": "/ˌreləˈtɪvəti/"},
    {"en": "remember", "ru": "помнить", "part_of_speech": "v", "pronunciation": "/rɪˈmembə(r)/"},
    {"en": "reporters", "ru": "журналисты", "part_of_speech": "pl n", "pronunciation": "/rɪˈpɔːtəz/"},
    {"en": "rocket", "ru": "ракета", "part_of_speech": "n", "pronunciation": "/ˈrɒkɪt/"},
    {"en": "rocks", "ru": "скалы", "part_of_speech": "pl n", "pronunciation": "/rɒks/"},
    {"en": "roses", "ru": "роза", "part_of_speech": "pl n", "pronunciation": "/ˈrəʊzɪz/"},
    {"en": "sailor", "ru": "моряк", "part_of_speech": "n", "pronunciation": "/ˈseɪlə(r)/"},
    {"en": "samples", "ru": "образцы", "part_of_speech": "pl n", "pronunciation": "/ˈsɑːmplz/"},
    {"en": "sell", "ru": "продавать", "part_of_speech": "v", "pronunciation": "/sel/"},
    {"en": "shirt", "ru": "рубашка", "part_of_speech": "n", "pronunciation": "/ʃɜːt/"},
    {"en": "slowly", "ru": "медленно", "part_of_speech": "adv", "pronunciation": "/ˈsləʊli/"},
    {"en": "space", "ru": "космос", "part_of_speech": "n", "pronunciation": "/speɪs/"},
    {"en": "spend", "ru": "тратить", "part_of_speech": "v", "pronunciation": "/spend/"},
    {"en": "step", "ru": "ступать. шагать", "part_of_speech": "v", "pronunciation": "/step/"},
    {"en": "suddenly", "ru": "вдруг, внезапно", "part_of_speech": "adv", "pronunciation": "/ˈsʌdənli/"},
    {"en": "summer", "ru": "лето", "part_of_speech": "n", "pronunciation": "/ˈsʌmə(r)/"},
    {"en": "surface", "ru": "поверхность", "part_of_speech": "n", "pronunciation": "/ˈsɜːfɪs/"},
    {"en": "sweets", "ru": "конфеты", "part_of_speech": "pl n", "pronunciation": "/swiːts/"},
    {"en": "term", "ru": "срок, период", "part_of_speech": "n", "pronunciation": "/tɜːm/"},
    {"en": "theme parks", "ru": "тематические парки", "part_of_speech": "pl n", "pronunciation": "/ˈθiːm pɑːks/"},
    {"en": "theory", "ru": "теория", "part_of_speech": "n", "pronunciation": "/ˈθɪəri/"},
    {"en": "umbrella", "ru": "зонт", "part_of_speech": "n", "pronunciation": "/ʌmˈbrelə/"},
    {"en": "voyage", "ru": "путешествие по морю", "part_of_speech": "n", "pronunciation": "/ˈvɔɪɪdʒ/"},
    {"en": "wake up", "ru": "просыпаться", "part_of_speech": "v", "pronunciation": "/weɪk ˈʌp/"},
    {"en": "wave", "ru": "махать, размахивать", "part_of_speech": "v", "pronunciation": "/weɪv/"},
    {"en": "whole", "ru": "целый, полный", "part_of_speech": "adj", "pronunciation": "/həʊl/"},
    {"en": "wool", "ru": "шерсть", "part_of_speech": "n", "pronunciation": "/wʊl/"}
]