const unit02 = [
    {"en": "accountant", "ru": "бухгалтер", "part_of_speech": "n", "pronunciation": "/əˈkaʊntənt/"},
    {"en": "actress", "ru": "актриса", "part_of_speech": "n", "pronunciation": "/ˈæktrəs/"},
    {"en": "airport", "ru": "аэропорт", "part_of_speech": "n", "pronunciation": "/ˈeəpɔːt/"},
    {"en": "animal", "ru": "животное", "part_of_speech": "n", "pronunciation": "/ˈænɪml/"},
    {"en": "architect", "ru": "архитектор", "part_of_speech": "n", "pronunciation": "/ˈɑːkɪtekt/"},
    {"en": "ballet dancer", "ru": "балетный танцор", "part_of_speech": "n", "pronunciation": "/ˈbæleɪ dɑːnsə(r)/"},
    {"en": "banker", "ru": "банкир", "part_of_speech": "n", "pronunciation": "/ˈbæŋkə(r)/"},
    {"en": "Belgium", "ru": "Бельгия", "part_of_speech": "n", "pronunciation": "/ˈbeldʒəm/"},
    {"en": "Bengali", "ru": "бенгальский", "part_of_speech": "adj", "pronunciation": "/beŋˈɡɔːli/"},
    {"en": "building", "ru": "здание", "part_of_speech": "n", "pronunciation": "/ˈbɪldɪŋ/"},
    {"en": "busy", "ru": "занятой", "part_of_speech": "adj", "pronunciation": "/ˈbɪzi/"},
    {"en": "capital", "ru": "столица", "part_of_speech": "n", "pronunciation": "/ˈkæpɪtl/"},
    {"en": "clock", "ru": "часы", "part_of_speech": "n", "pronunciation": "/klɒk/"},
    {"en": "come", "ru": "приходить", "part_of_speech": "v", "pronunciation": "/kʌm/"},
    {"en": "cost", "ru": "стоить", "part_of_speech": "v", "pronunciation": "/kɒst/"},
    {"en": "country", "ru": "страна", "part_of_speech": "n", "pronunciation": "/ˈkʌntri/"},
    {"en": "cut", "ru": "резать", "part_of_speech": "v", "pronunciation": "/kʌt/"},
    {"en": "dentist", "ru": "стоматолог", "part_of_speech": "n", "pronunciation": "/ˈdentɪst/"},
    {"en": "desert", "ru": "пустыня", "part_of_speech": "n", "pronunciation": "/ˈdezət/"},
    {"en": "design", "ru": "дизайн", "part_of_speech": "v", "pronunciation": "/dɪˈzaɪn/"},
    {"en": "disc jockey", "ru": "диджей", "part_of_speech": "n", "pronunciation": "/ˈdɪsk dʒɒki/"},
    {"en": "earn", "ru": "заработать", "part_of_speech": "v", "pronunciation": "/ɜːn/"},
    {"en": "engineer", "ru": "инженер", "part_of_speech": "n", "pronunciation": "/endʒəˈnɪə(r)/"},
    {"en": "exactly", "ru": "точно", "part_of_speech": "adv", "pronunciation": "/ɪɡˈzæktli/"},
    {"en": "exciting", "ru": "увлекательный, захватывающий", "part_of_speech": "adj", "pronunciation": "/ɪkˈsaɪtɪŋ/"},
    {"en": "famous", "ru": "известный", "part_of_speech": "adj", "pronunciation": "/ˈfeɪməs/"},
    {"en": "France", "ru": "Франция", "part_of_speech": "n", "pronunciation": "/frɑːns/"},
    {"en": "free time", "ru": "свободное время", "part_of_speech": "n", "pronunciation": "/friː taɪm/"},
    {"en": "go", "ru": "идти", "part_of_speech": "v", "pronunciation": "/ɡəʊ/"},
    {"en": "gym", "ru": "тренажерный зал", "part_of_speech": "n", "pronunciation": "/dʒɪm/"},
    {"en": "hair", "ru": "волосы", "part_of_speech": "n", "pronunciation": "/heə(r)/"},
    {"en": "hairdresser", "ru": "парикмахер", "part_of_speech": "n", "pronunciation": "/ˈheədresə(r)/"},
    {"en": "have", "ru": "иметь", "part_of_speech": "v", "pronunciation": "/hæv/"},
    {"en": "history", "ru": "история", "part_of_speech": "n", "pronunciation": "/ˈhɪstri/"},
    {"en": "hotel", "ru": "отель", "part_of_speech": "n", "pronunciation": "/həʊˈtel/"},
    {"en": "hour", "ru": "час", "part_of_speech": "n", "pronunciation": "/ˈaʊə(r)/"},
    {"en": "housework", "ru": "домашняя работа", "part_of_speech": "n", "pronunciation": "/ˈhaʊswɜːk/"},
    {"en": "hurry", "ru": "спешить", "part_of_speech": "v", "pronunciation": "/ˈhʌri/"},
    {"en": "India", "ru": "Индия", "part_of_speech": "n", "pronunciation": "/ˈɪndiə/"},
    {"en": "Internet", "ru": "Интернет", "part_of_speech": "n", "pronunciation": "/ˈɪntənet/"},
    {"en": "interpreter", "ru": "переводчик", "part_of_speech": "n", "pronunciation": "/ɪnˈtɜːprɪtə(r)/"},
    {"en": "job", "ru": "работа", "part_of_speech": "n", "pronunciation": "/dʒɒb/"},
    {"en": "journalist", "ru": "журналист", "part_of_speech": "n", "pronunciation": "/ˈdʒɜːnəlɪst/"},
    {"en": "law firm", "ru": "юридическая фирма", "part_of_speech": "n", "pronunciation": "/lɔː fɜːm/"},
    {"en": "lawyer", "ru": "адвокат", "part_of_speech": "n", "pronunciation": "/ˈlɔːjə(r)/"},
    {"en": "learn", "ru": "учить", "part_of_speech": "v", "pronunciation": "/lɜːn/"},
    {"en": "lucky", "ru": "счастливый", "part_of_speech": "adj", "pronunciation": "/ˈlʌki/"},
    {"en": "lunch", "ru": "обед", "part_of_speech": "n", "pronunciation": "/lʌntʃ/"},
    {"en": "many", "ru": "много", "part_of_speech": "pron", "pronunciation": "/ˈmeni/"},
    {"en": "maths", "ru": "математика", "part_of_speech": "n", "pronunciation": "/mæθs/"},
    {"en": "model", "ru": "модель", "part_of_speech": "n", "pronunciation": "/ˈmɒdl/"},
    {"en": "money", "ru": "деньги", "part_of_speech": "n", "pronunciation": "/ˈmʌni/"},
    {"en": "natural", "ru": "естественный", "part_of_speech": "adj", "pronunciation": "/ˈnætrəl/"},
    {"en": "never", "ru": "никогда", "part_of_speech": "adv", "pronunciation": "/ˈnevə(r)/"},
    {"en": "New Zealand", "ru": "Новая Зеландия", "part_of_speech": "n", "pronunciation": "/ˌnjuː ˈziːlənd/"},
    {"en": "news story", "ru": "новостная история", "part_of_speech": "n", "pronunciation": "/njuːz ˈstɔːri/"},
    {"en": "newspaper", "ru": "газета", "part_of_speech": "n", "pronunciation": "/ˈnjuːzpeɪpə(r)/"},
    {"en": "nurse", "ru": "медсестра", "part_of_speech": "n", "pronunciation": "/nɜːs/"},
    {"en": "oil rig", "ru": "нефтяная платформа", "part_of_speech": "n", "pronunciation": "/ˈɔɪl rɪɡ/"},
    {"en": "outdoors", "ru": "на свежем воздухе, с наружи", "part_of_speech": "n", "pronunciation": "/ˌaʊtˈdɔːz/"},
    {"en": "physics", "ru": "физика", "part_of_speech": "n", "pronunciation": "/ˈfɪzɪks/"},
    {"en": "play", "ru": "играть", "part_of_speech": "v", "pronunciation": "/pleɪ/"},
    {"en": "poor", "ru": "бедный", "part_of_speech": "adj", "pronunciation": "/pɔː(r)/"},
    {"en": "pop star", "ru": "поп-звезда", "part_of_speech": "n", "pronunciation": "/pɒp stɑː(r)/"},
    {"en": "reading", "ru": "чтение", "part_of_speech": "n", "pronunciation": "/ˈriːdɪŋ/"},
    {"en": "receptionist", "ru": "секретарь", "part_of_speech": "n", "pronunciation": "/rɪˈsepʃənɪst/"},
    {"en": "salary", "ru": "зарплата", "part_of_speech": "n", "pronunciation": "/ˈsæləri/"},
    {"en": "Scotland", "ru": "Шотландия", "part_of_speech": "n", "pronunciation": "/ˈskɒtlənd/"},
    {"en": "snooker", "ru": "снукер", "part_of_speech": "n", "pronunciation": "/ˈsnuːkə(r)/"},
    {"en": "sometimes", "ru": "иногда", "part_of_speech": "adv", "pronunciation": "/ˈsʌmtaɪmz/"},
    {"en": "Spanish", "ru": "испанский", "part_of_speech": "adj", "pronunciation": "/ˈspænɪʃ/"},
    {"en": "street", "ru": "улица", "part_of_speech": "n", "pronunciation": "/striːt/"},
    {"en": "study", "ru": "учить", "part_of_speech": "v", "pronunciation": "/ˈstʌdi/"},
    {"en": "taxi driver", "ru": "таксист", "part_of_speech": "n", "pronunciation": "/ˈtæksi ˌdraɪvə(r)/"},
    {"en": "teeth", "ru": "зубы", "part_of_speech": "n", "pronunciation": "/tiːθ/"},
    {"en": "time", "ru": "время", "part_of_speech": "n", "pronunciation": "/taɪm/"},
    {"en": "tired", "ru": "усталый", "part_of_speech": "adj", "pronunciation": "/ˈtaɪəd/"},
    {"en": "town", "ru": "город", "part_of_speech": "n", "pronunciation": "/taʊn/"},
    {"en": "travel", "ru": "путешествовать", "part_of_speech": "v", "pronunciation": "/ˈtrævl/"},
    {"en": "TV", "ru": "телевизор", "part_of_speech": "n", "pronunciation": "/ˌtiː ˈviː/"},
    {"en": "village", "ru": "деревня", "part_of_speech": "n", "pronunciation": "/ˈvɪlɪdʒ/"},
    {"en": "visit", "ru": "посетить", "part_of_speech": "v", "pronunciation": "/ˈvɪzɪt/"},
    {"en": "walk", "ru": "гулять", "part_of_speech": "v", "pronunciation": "/wɔːk/"},
    {"en": "watch", "ru": "смотреть", "part_of_speech": "v", "pronunciation": "/wɒtʃ/"},
    {"en": "work", "ru": "работать", "part_of_speech": "v", "pronunciation": "/wɜːk/"},
    {"en": "world", "ru": "мир", "part_of_speech": "n", "pronunciation": "/wɜːld/"},
    {"en": "write", "ru": "писать", "part_of_speech": "v", "pronunciation": "/raɪt/"},
    {"en": "zoologist", "ru": "зоолог", "part_of_speech": "n", "pronunciation": "/zuˈɒlədʒɪst/"},

]