const unit12 = [
    {"en": "acres", "ru": "акры", "part_of_speech": "pl n", "pronunciation": "/ˈeɪkəz/"},
    {"en": "acts", "ru": "действия", "part_of_speech": "pl n", "pronunciation": "/ækts/"},
    {"en": "atmosphere", "ru": "атмосфера", "part_of_speech": "n", "pronunciation": "/ˈætməsfɪə(r)/"},
    {"en": "attend", "ru": "посещать", "part_of_speech": "v", "pronunciation": "/əˈtend/"},
    {"en": "Australia", "ru": "Австралия", "part_of_speech": "n", "pronunciation": "/ɒˈstreɪlɪə/"},
    {"en": "Brazil", "ru": "Бразилия", "part_of_speech": "n", "pronunciation": "/brəˈzɪl/"},
    {"en": "brilliant", "ru": "блестящий", "part_of_speech": "adj", "pronunciation": "/ˈbrɪliənt/"},
    {"en": "cancel", "ru": "отменить", "part_of_speech": "v", "pronunciation": "/ˈkænsl/"},
    {"en": "check in", "ru": "зарегистрироваться", "part_of_speech": "v", "pronunciation": "/tʃek ˈɪn/"},
    {"en": "China", "ru": "Китай", "part_of_speech": "n", "pronunciation": "/ˈtʃaɪnə/"},
    {"en": "cider", "ru": "сидр", "part_of_speech": "n", "pronunciation": "/ˈsaɪdə(r)/"},
    {"en": "colleague", "ru": "коллега", "part_of_speech": "n", "pronunciation": "/ˈkɒliːɡ/"},
    {"en": "continual", "ru": "непрерывный", "part_of_speech": "adj", "pronunciation": "/kənˈtɪnjuəl/"},
    {"en": "crowd", "ru": "толпа", "part_of_speech": "n", "pronunciation": "/kraʊd/"},
    {"en": "death", "ru": "смерть", "part_of_speech": "n", "pronunciation": "/deθ/"},
    {"en": "definite", "ru": "определенный", "part_of_speech": "adj", "pronunciation": "/ˈdefɪnət/"},
    {"en": "departures board", "ru": "табло отправлений", "part_of_speech": "n", "pronunciation": "/dɪˈpɑːtʃəz bɔːd/"},
    {"en": "disappointed", "ru": "разочарованный", "part_of_speech": "adj", "pronunciation": "/ˌdɪsəˈpɔɪntɪd/"},
    {"en": "Egypt", "ru": "Египет", "part_of_speech": "n", "pronunciation": "/iːdʒɪpt/"},
    {"en": "ever", "ru": "когда-либо", "part_of_speech": "adv", "pronunciation": "/ˈevə(r)/"},
    {"en": "express", "ru": "выражать", "part_of_speech": "v", "pronunciation": "/ɪkˈspres/"},
    {"en": "fail", "ru": "терпеть неудачу", "part_of_speech": "v", "pronunciation": "/feɪl/"},
    {"en": "festival", "ru": "фестиваль", "part_of_speech": "n", "pronunciation": "/ˈfestɪvl/"},
    {"en": "festival goers", "ru": "посетители фестиваля", "part_of_speech": "pl n", "pronunciation": "/ˈfestɪvl ˈɡəʊəz/"},
    {"en": "get on", "ru": "сесть на (транспорт)", "part_of_speech": "v", "pronunciation": "/ɡet ɒn/"},
    {"en": "Great Britain", "ru": "Великобритания", "part_of_speech": "n", "pronunciation": "/ˌɡreɪt ˈbrɪtn/"},
    {"en": "Greece", "ru": "Греция", "part_of_speech": "n", "pronunciation": "/griːs/"},
    {"en": "hand luggage", "ru": "ручная кладь", "part_of_speech": "n", "pronunciation": "/ˈhænd lʌɡɪdʒ/"},
    {"en": "Italy", "ru": "Италия", "part_of_speech": "n", "pronunciation": "/ˈɪtəli/"},
    {"en": "Japan", "ru": "Япония", "part_of_speech": "n", "pronunciation": "/dʒəpæn/"},
    {"en": "jumbo jet", "ru": "гигантский самолет", "part_of_speech": "n", "pronunciation": "/ˌdʒʌmbəʊ ˈdʒet/"},
    {"en": "just", "ru": "только", "part_of_speech": "adv", "pronunciation": "/dʒʌst/"},
    {"en": "knees", "ru": "колени", "part_of_speech": "pl n", "pronunciation": "/niːz/"},
    {"en": "luggage", "ru": "багаж", "part_of_speech": "n", "pronunciation": "/ˈlʌɡɪdʒ/"},
    {"en": "memories", "ru": "воспоминания", "part_of_speech": "pl n", "pronunciation": "/ˈmeməriz/"},
    {"en": "mud", "ru": "грязь", "part_of_speech": "n", "pronunciation": "/mʌd/"},
    {"en": "noisy", "ru": "шумный", "part_of_speech": "adj", "pronunciation": "/ˈnɔɪzi/"},
    {"en": "open-air", "ru": "на открытом воздухе", "part_of_speech": "adj", "pronunciation": "/ˌəʊpən ˈeə(r)/"},
    {"en": "packing", "ru": "упаковка", "part_of_speech": "n", "pronunciation": "/ˈpækɪŋ/"},
    {"en": "performer", "ru": "исполнитель", "part_of_speech": "n", "pronunciation": "/pəˈfɔːmə(r)/"},
    {"en": "piece", "ru": "кусок", "part_of_speech": "n", "pronunciation": "/piːs/"},
    {"en": "platform", "ru": "платформа", "part_of_speech": "n", "pronunciation": "/ˈplætfɔːm/"},
    {"en": "poem", "ru": "стихотворение", "part_of_speech": "n", "pronunciation": "/ˈpəʊɪm/"},
    {"en": "print", "ru": "печатать", "part_of_speech": "v", "pronunciation": "/prɪnt/"},
    {"en": "queue", "ru": "очередь", "part_of_speech": "n", "pronunciation": "/kjuː/"},
    {"en": "refer to", "ru": "ссылаться на", "part_of_speech": "v", "pronunciation": "/rɪˈfɜː tə/"},
    {"en": "rise", "ru": "восходить", "part_of_speech": "v", "pronunciation": "/raɪz/"},
    {"en": "rock concert", "ru": "рок-концерт", "part_of_speech": "n", "pronunciation": "/rɒk ˈkɒnsət/"},
    {"en": "rubbish", "ru": "мусор", "part_of_speech": "adj", "pronunciation": "/ˈrʌbɪʃ/"},
    {"en": "savings", "ru": "сбережения", "part_of_speech": "pl n", "pronunciation": "/ˈseɪvɪŋz/"},
    {"en": "scuba dive", "ru": "заниматься подводным плаванием", "part_of_speech": "v", "pronunciation": "/ˈskuːbə daɪv/"},
    {"en": "security", "ru": "безопасность", "part_of_speech": "n", "pronunciation": "/sɪˈkjʊərəti/"},
    {"en": "slogan", "ru": "слоган", "part_of_speech": "n", "pronunciation": "/ˈsləʊɡən/"},
    {"en": "stage", "ru": "сцена", "part_of_speech": "n", "pronunciation": "/steɪdʒ/"},
    {"en": "sunshine", "ru": "солнечный свет", "part_of_speech": "n", "pronunciation": "/ˈsʌnʃaɪn/"},
    {"en": "taxi", "ru": "такси", "part_of_speech": "n", "pronunciation": "/ˈtæksi/"},
    {"en": "tent", "ru": "палатка", "part_of_speech": "n", "pronunciation": "/tent/"},
    {"en": "the US", "ru": "США", "part_of_speech": "n", "pronunciation": "/ðə ju ˈes/"},
    {"en": "trip", "ru": "поездка", "part_of_speech": "n", "pronunciation": "/trɪp/"},
    {"en": "van", "ru": "фургон", "part_of_speech": "n", "pronunciation": "/væn/"},
    {"en": "yet", "ru": "еще", "part_of_speech": "adv", "pronunciation": "/jet/"}
]