const unit09 = [
    {"en": "accent", "ru": "акцент", "part_of_speech": "n", "pronunciation": "/ˈæksent/"},
    {"en": "air", "ru": "воздух", "part_of_speech": "n", "pronunciation": "/eə(r)/"},
    {"en": "architecture", "ru": "архитектура", "part_of_speech": "n", "pronunciation": "/ˈɑːkɪtektʃə(r)/"},
    {"en": "area", "ru": "область, район", "part_of_speech": "n", "pronunciation": "/ˈeəriə/"},
    {"en": "artists", "ru": "художники", "part_of_speech": "pl n", "pronunciation": "/ˈɑːtɪsts/"},
    {"en": "banks", "ru": "банки", "part_of_speech": "pl n", "pronunciation": "/bæŋks/"},
    {"en": "blossom", "ru": "цветение", "part_of_speech": "n", "pronunciation": "/ˈblɒsəm/"},
    {"en": "capital city", "ru": "столица", "part_of_speech": "n", "pronunciation": "/ˈkæpɪtl ˈsɪti/"},
    {"en": "careful", "ru": "осторожный", "part_of_speech": "adj", "pronunciation": "/ˈkeəfl/"},
    {"en": "celebrities", "ru": "знаменитости", "part_of_speech": "pl n", "pronunciation": "/səˈlebrətiz/"},
    {"en": "central", "ru": "центральный", "part_of_speech": "adj", "pronunciation": "/ˈsentrəl/"},
    {"en": "change", "ru": "менять", "part_of_speech": "v", "pronunciation": "/tʃeɪndʒ/"},
    {"en": "cherry", "ru": "вишня", "part_of_speech": "n", "pronunciation": "/ˈtʃeri/"},
    {"en": "climate", "ru": "климат", "part_of_speech": "n", "pronunciation": "/ˈklaɪmət/"},
    {"en": "clubs", "ru": "клубы", "part_of_speech": "pl n", "pronunciation": "/klʌbz/"},
    {"en": "church", "ru": "церковь", "part_of_speech": "n", "pronunciation": "/tʃɜːtʃ/"},
    {"en": "coast", "ru": "побережье", "part_of_speech": "n", "pronunciation": "/kəʊst/"},
    {"en": "colonial", "ru": "колониальный", "part_of_speech": "adj", "pronunciation": "/kəˈləʊniəl/"},
    {"en": "commercial centres", "ru": "комерческий центры", "part_of_speech": "pl n", "pronunciation": "/kəˈmɜːʃl ˈsentəz/"},
    {"en": "commuter", "ru": "пассажир", "part_of_speech": "n", "pronunciation": "/kəˈmjuːtə(r)/"},
    {"en": "cool", "ru": "крутой", "part_of_speech": "adj", "pronunciation": "/kuːl/"},
    {"en": "crowded", "ru": "переполненный", "part_of_speech": "adj", "pronunciation": "/ˈkraʊdɪd/"},
    {"en": "culture", "ru": "культура", "part_of_speech": "n", "pronunciation": "/ˈkʌltʃə(r)/"},
    {"en": "earthquake", "ru": "землетрясение", "part_of_speech": "n", "pronunciation": "/ˈɜːθkweɪk/"},
    {"en": "east", "ru": "восток", "part_of_speech": "n", "pronunciation": "/iːst/"},
    {"en": "electricity", "ru": "электричество", "part_of_speech": "n", "pronunciation": "/ɪˌlekˈtrɪsəti/"},
    {"en": "elegant", "ru": "элегантный", "part_of_speech": "adj", "pronunciation": "/ˈelɪɡənt/"},
    {"en": "emperor", "ru": "император", "part_of_speech": "n", "pronunciation": "/ˈempərə(r)/"},
    {"en": "empire", "ru": "империя", "part_of_speech": "n", "pronunciation": "/ˈempaɪə(r)/"},
    {"en": "Englishman", "ru": "англичанин", "part_of_speech": "n", "pronunciation": "/ˈɪŋɡlɪʃmən/"},
    {"en": "experience", "ru": "опыт", "part_of_speech": "n", "pronunciation": "/ɪkˈspɪəriəns/"},
    {"en": "extreme", "ru": "экстремальный", "part_of_speech": "adj", "pronunciation": "/ɪkˈstriːm/"},
    {"en": "fashion", "ru": "мода", "part_of_speech": "n", "pronunciation": "/ˈfæʃn/"},
    {"en": "fishing", "ru": "рыболовство", "part_of_speech": "n", "pronunciation": "/ˈfɪʃɪŋ/"},
    {"en": "food", "ru": "еда", "part_of_speech": "n", "pronunciation": "/fuːd/"},
    {"en": "foreigners", "ru": "иностранцы", "part_of_speech": "pl n", "pronunciation": "/ˈfɒrənəz/"},
    {"en": "generally", "ru": "обычно", "part_of_speech": "adv", "pronunciation": "/ˈdʒenrəli/"},
    {"en": "gold", "ru": "золото", "part_of_speech": "n", "pronunciation": "/ɡəʊld/"},
    {"en": "goods", "ru": "товары", "part_of_speech": "pl n", "pronunciation": "/ɡʊdz/"},
    {"en": "handicrafts", "ru": "изделия ручной работы", "part_of_speech": "pl n", "pronunciation": "/ˈhændikrɑːfts/"},
    {"en": "headquarters", "ru": "штаб-квартира", "part_of_speech": "n", "pronunciation": "/ˌhedˈkwɔːtəz/"},
    {"en": "high-class", "ru": "высший класс", "part_of_speech": "adj", "pronunciation": "/ˌhaɪ ˈklɑːs/"},
    {"en": "hill", "ru": "холм", "part_of_speech": "n", "pronunciation": "/hɪl/"},
    {"en": "historic", "ru": "исторический", "part_of_speech": "adj", "pronunciation": "/hɪˈstɒrɪk/"},
    {"en": "huge", "ru": "огромный", "part_of_speech": "adj", "pronunciation": "/hjuːdʒ/"},
    {"en": "humid", "ru": "влажный", "part_of_speech": "adj", "pronunciation": "/ˈhjuːmɪd/"},
    {"en": "hundreds", "ru": "сотни", "part_of_speech": "pl n", "pronunciation": "/ˈhʌndrədz/"},
    {"en": "independence", "ru": "независимость", "part_of_speech": "n", "pronunciation": "/ˌɪndɪˈpendəns/"},
    {"en": "industry", "ru": "промышленность", "part_of_speech": "n", "pronunciation": "/ˈɪndəstri/"},
    {"en": "invade", "ru": "вторгаться", "part_of_speech": "v", "pronunciation": "/ɪnˈveɪd/"},
    {"en": "jewellery", "ru": "ювелирные изделия", "part_of_speech": "n", "pronunciation": "/ˈdʒuːəlri/"},
    {"en": "kilometre", "ru": "километр", "part_of_speech": "n", "pronunciation": "/kɪˈlɒmɪtə(r)/"},
    {"en": "latest", "ru": "последний", "part_of_speech": "adj", "pronunciation": "/ˈleɪtɪst/"},
    {"en": "loud", "ru": "громкий, шумный", "part_of_speech": "adj", "pronunciation": "/laʊd/"},
    {"en": "market", "ru": "рынок", "part_of_speech": "n", "pronunciation": "/ˈmɑːkɪt/"},
    {"en": "megacity", "ru": "мегаполис", "part_of_speech": "n", "pronunciation": "/ˈmeɡəˌsɪti/"},
    {"en": "Metro", "ru": "метро", "part_of_speech": "n", "pronunciation": "/ˈmetrəʊ/"},
    {"en": "mountains", "ru": "горы", "part_of_speech": "pl n", "pronunciation": "/ˈmaʊntənz/"},
    {"en": "multicultural", "ru": "мультикультурный", "part_of_speech": "adj", "pronunciation": "/ˌmʌltiˈkʌltʃərəl/"},
    {"en": "mysterious", "ru": "таинственный", "part_of_speech": "adj", "pronunciation": "/mɪˈstɪəriəs/"},
    {"en": "nightclub", "ru": "ночной клуб", "part_of_speech": "n", "pronunciation": "/ˈnaɪtklʌb/"},
    {"en": "north", "ru": "север", "part_of_speech": "n", "pronunciation": "/nɔːθ/"},
    {"en": "of course", "ru": "конечно", "part_of_speech": "phrase", "pronunciation": "/ɒv kɔːs/"},
    {"en": "orange", "ru": "оранжевый", "part_of_speech": "adj", "pronunciation": "/ˈɒrɪndʒ/"},
    {"en": "originally", "ru": "изначально", "part_of_speech": "adv", "pronunciation": "/əˈrɪdʒənəli/"},
    {"en": "palace", "ru": "дворец", "part_of_speech": "n", "pronunciation": "/ˈpæləs/"},
    {"en": "pedestrian crossing", "ru": "пешеходный переход", "part_of_speech": "n", "pronunciation": "/pəˈdestrɪən krɒsɪŋ/"},
    {"en": "pink", "ru": "розовый", "part_of_speech": "adj", "pronunciation": "/pɪŋk/"},
    {"en": "polite", "ru": "вежливый", "part_of_speech": "adj", "pronunciation": "/pəˈlaɪt/"},
    {"en": "pollution", "ru": "загрязнение", "part_of_speech": "n", "pronunciation": "/pəˈluːʃn/"},
    {"en": "population", "ru": "население", "part_of_speech": "n", "pronunciation": "/ˌpɒpjuˈleɪʃn/"},
    {"en": "poverty", "ru": "бедность", "part_of_speech": "n", "pronunciation": "/ˈpɒvəti/"},
    {"en": "prefer", "ru": "предпочитать", "part_of_speech": "v", "pronunciation": "/prɪˈfɜː(r)/"},
    {"en": "produce", "ru": "производить", "part_of_speech": "v", "pronunciation": "/prəˈdjuːs/"},
    {"en": "public bath", "ru": "публичная баня", "part_of_speech": "n", "pronunciation": "/pʌblɪk ˈbɑːθ/"},
    {"en": "public transport", "ru": "общественный транспорт", "part_of_speech": "n", "pronunciation": "/pʌblɪk ˈtrænspɔːt/"},
    {"en": "quality", "ru": "качество", "part_of_speech": "n", "pronunciation": "/ˈkwɒləti/"},
    {"en": "quieter", "ru": "тихий", "part_of_speech": "adj", "pronunciation": "/ˈkwaɪətə(r)/"},
    {"en": "railway system", "ru": "железнодорожная система", "part_of_speech": "n", "pronunciation": "/ˈreɪlweɪ ˈsɪstəm/"},
    {"en": "rainy", "ru": "дождливый", "part_of_speech": "adj", "pronunciation": "/ˈreɪni/"},
    {"en": "river", "ru": "река", "part_of_speech": "n", "pronunciation": "/ˈrɪvə(r)/"},
    {"en": "romantic", "ru": "романтичный", "part_of_speech": "adj", "pronunciation": "/rəʊˈmæntɪk/"},
    {"en": "roundabout", "ru": "круговое движение", "part_of_speech": "n", "pronunciation": "/raʊndəbaʊt/"},
    {"en": "safe", "ru": "безопасный", "part_of_speech": "adj", "pronunciation": "/seɪf/"},
    {"en": "sanitation", "ru": "санитария", "part_of_speech": "n", "pronunciation": "/ˌsænɪˈteɪʃn/"},
    {"en": "season", "ru": "сезон", "part_of_speech": "n", "pronunciation": "/ˈsiːzn/"},
    {"en": "shrine", "ru": "святилище", "part_of_speech": "n", "pronunciation": "/ʃraɪn/"},
    {"en": "skyscrapers", "ru": "небоскребы", "part_of_speech": "pl n", "pronunciation": "/ˈskaɪskreɪpəz/"},
    {"en": "slums", "ru": "трущобы", "part_of_speech": "pl n", "pronunciation": "/slʌmz/"},
    {"en": "snacks", "ru": "закуски", "part_of_speech": "pl n", "pronunciation": "/snæks/"},
    {"en": "somewhere", "ru": "где-то", "part_of_speech": "adv", "pronunciation": "/ˈsʌmweə(r)/"},
    {"en": "south", "ru": "юг", "part_of_speech": "n", "pronunciation": "/saʊθ/"},
    {"en": "spring", "ru": "весна", "part_of_speech": "n", "pronunciation": "/sprɪŋ/"},
    {"en": "square", "ru": "площадь", "part_of_speech": "n", "pronunciation": "/skweə(r)/"},
    {"en": "stone", "ru": "каменный", "part_of_speech": "adj", "pronunciation": "/stəʊn/"},
    {"en": "subway system", "ru": "метро", "part_of_speech": "n", "pronunciation": "/ˈsʌbweɪ sɪstəm/"},
    {"en": "sunrise", "ru": "восход солнца", "part_of_speech": "n", "pronunciation": "/ˈsʌnraɪz/"},
    {"en": "sunset", "ru": "закат солнца", "part_of_speech": "n", "pronunciation": "/ˈsʌnset/"},
    {"en": "surrounded", "ru": "окружённый", "part_of_speech": "adj", "pronunciation": "/səˈraʊndɪd/"},
    {"en": "take place", "ru": "происходить, иметь место", "part_of_speech": "v", "pronunciation": "/teɪk pleɪs/"},
    {"en": "tall", "ru": "высокий", "part_of_speech": "adj", "pronunciation": "/tɔːl/"},
    {"en": "tattoo", "ru": "татуировка", "part_of_speech": "n", "pronunciation": "/təˈtuː/"},
    {"en": "temple", "ru": "храм", "part_of_speech": "n", "pronunciation": "/ˈtempl/"},
    {"en": "theatre", "ru": "театр", "part_of_speech": "n", "pronunciation": "/ˈθɪətə(r)/"},
    {"en": "tourist attraction", "ru": "туристическая достопримечательность", "part_of_speech": "n", "pronunciation": "/ˈtɔːrɪst əˈtrækʃn/"},
    {"en": "toy shop", "ru": "магазин игрушек", "part_of_speech": "n", "pronunciation": "/tɔɪ ʃɒp/"},
    {"en": "traditional", "ru": "традиционный", "part_of_speech": "adj", "pronunciation": "/trəˈdɪʃənl/"},
    {"en": "traffic lights", "ru": "светофор", "part_of_speech": "pl n", "pronunciation": "/ˈtræfɪk laɪts/"},
    {"en": "traffic sign", "ru": "дорожный знак", "part_of_speech": "n", "pronunciation": "/ˈtræfɪk saɪn/"},
    {"en": "transport", "ru": "транспорт", "part_of_speech": "n", "pronunciation": "/ˈtrænspɔːt/"},
    {"en": "true", "ru": "истинный", "part_of_speech": "adj", "pronunciation": "/truː/"},
    {"en": "unique", "ru": "уникальный", "part_of_speech": "adj", "pronunciation": "/juˈniːk/"},
    {"en": "up-to-date", "ru": "современный", "part_of_speech": "adj", "pronunciation": "/ˌʌp tə ˈdeɪt/"},
    {"en": "valley", "ru": "долина", "part_of_speech": "n", "pronunciation": "/ˈvæli/"},
    {"en": "variety", "ru": "разнообразие", "part_of_speech": "n", "pronunciation": "/vəˈraɪəti/"},
    {"en": "wet", "ru": "мокрый", "part_of_speech": "adj", "pronunciation": "/wet/"},
    {"en": "wood", "ru": "дерево", "part_of_speech": "n", "pronunciation": "/wʊd/"}
]