const unit04 = [
    {"en": "above", "ru": "выше", "part_of_speech": "prep", "pronunciation": "/əˈbʌv/"},
    {"en": "address book", "ru": "адресная книга", "part_of_speech": "n", "pronunciation": "/əˈdres bʊk/"},
    {"en": "amazing", "ru": "удивительный", "part_of_speech": "adj", "pronunciation": "/əˈmeɪzɪŋ/"},
    {"en": "armchair", "ru": "кресло", "part_of_speech": "n", "pronunciation": "/ˈɑːmtʃeə/"},
    {"en": "awful", "ru": "ужасный", "part_of_speech": "adj", "pronunciation": "/ˈɔːfl/"},
    {"en": "balcony", "ru": "балкон", "part_of_speech": "n", "pronunciation": "/ˈbælkəni/"},
    {"en": "bathroom", "ru": "ванная", "part_of_speech": "n", "pronunciation": "/ˈbɑːθruːm/"},
    {"en": "bedroom", "ru": "спальня", "part_of_speech": "n", "pronunciation": "/ˈbedruːm/"},
    {"en": "bench", "ru": "скамейка", "part_of_speech": "n", "pronunciation": "/bentʃ/"},
    {"en": "birthday", "ru": "день рождения", "part_of_speech": "n", "pronunciation": "/ˈbɜːθdeɪ/"},
    {"en": "bookshelves", "ru": "книжные полки", "part_of_speech": "pl n", "pronunciation": "/ˈbʊkʃelvz/"},
    {"en": "boss", "ru": "босс", "part_of_speech": "n", "pronunciation": "/bɒs/"},
    {"en": "bowling alley", "ru": "боулинг", "part_of_speech": "n", "pronunciation": "/ˌbəʊliŋ æli/"},
    {"en": "bus fare", "ru": "стоимость проезда", "part_of_speech": "n", "pronunciation": "/bʌs feə(r)/"},
    {"en": "bus stop", "ru": "автобусная остановка", "part_of_speech": "n", "pronunciation": "/ˈbʌs stɒp/"},
    {"en": "carpet", "ru": "ковёр", "part_of_speech": "n", "pronunciation": "/ˈkɑːpɪt/"},
    {"en": "cathedral", "ru": "собор", "part_of_speech": "n", "pronunciation": "/kəˈθiːdrəl/"},
    {"en": "chemist’s", "ru": "аптека", "part_of_speech": "n", "pronunciation": "/ˈkemɪsts/"},
    {"en": "choose", "ru": "выбирать", "part_of_speech": "v", "pronunciation": "/tʃuːz/"},
    {"en": "clothes", "ru": "одежда", "part_of_speech": "pl n", "pronunciation": "/kləʊðz/"},
    {"en": "coat", "ru": "пальто", "part_of_speech": "n", "pronunciation": "/kəʊt/"},
    {"en": "colour", "ru": "цвет", "part_of_speech": "n", "pronunciation": "/ˈkʌlə/"},
    {"en": "comfortable", "ru": "комфортный", "part_of_speech": "adj", "pronunciation": "/ˈkʌmfətəbl/"},
    {"en": "cooker", "ru": "плита", "part_of_speech": "n", "pronunciation": "/ˈkʊkə(r)/"},
    {"en": "cup", "ru": "чашка", "part_of_speech": "n", "pronunciation": "/kʌp/"},
    {"en": "curtains", "ru": "шторы", "part_of_speech": "pl n", "pronunciation": "/ˈkɜːtnz/"},
    {"en": "desk", "ru": "письменный стол", "part_of_speech": "n", "pronunciation": "/desk/"},
    {"en": "diary", "ru": "дневник", "part_of_speech": "n", "pronunciation": "/ˈdaɪəri/"},
    {"en": "dining room", "ru": "столовая", "part_of_speech": "n", "pronunciation": "/ˈdaɪnɪŋ ruːm/"},
    {"en": "dinner", "ru": "ужин", "part_of_speech": "n", "pronunciation": "/ˈdɪnə(r)/"},
    {"en": "DVD player", "ru": "DVD-плеер", "part_of_speech": "n", "pronunciation": "/ˌdiː viː ˈdiː ˈpleɪə(r)/"},
    {"en": "eat", "ru": "есть", "part_of_speech": "v", "pronunciation": "/iːt/"},
    {"en": "elevator", "ru": "лифт", "part_of_speech": "n", "pronunciation": "/ˈelɪveɪtə(r)/"},
    {"en": "excellent", "ru": "отличный", "part_of_speech": "adj", "pronunciation": "/ˈeksələnt/"},
    {"en": "fabulous", "ru": "сказочный", "part_of_speech": "adj", "pronunciation": "/ˈfæbjələs/"},
    {"en": "fantastic", "ru": "фантастический", "part_of_speech": "adj", "pronunciation": "/fænˈtæstɪk/"},
    {"en": "fireplace", "ru": "камин", "part_of_speech": "n", "pronunciation": "/ˈfaɪəpleɪs/"},
    {"en": "first floor", "ru": "первый этаж", "part_of_speech": "n", "pronunciation": "/ˌfɜːst ˈflɔː(r)/"},
    {"en": "flat", "ru": "квартира", "part_of_speech": "n", "pronunciation": "/flæt/"},
    {"en": "fridge", "ru": "холодильник", "part_of_speech": "n", "pronunciation": "/frɪdʒ/"},
    {"en": "fruit", "ru": "фрукты", "part_of_speech": "n", "pronunciation": "/fruːt/"},
    {"en": "furniture", "ru": "мебель", "part_of_speech": "n", "pronunciation": "/ˈfɜːnɪtʃə(r)/"},
    {"en": "gardener", "ru": "садовник", "part_of_speech": "n", "pronunciation": "/ˈɡɑːdnə(r)/"},
    {"en": "gift", "ru": "подарок", "part_of_speech": "n", "pronunciation": "/ɡɪft/"},
    {"en": "glass", "ru": "стекло", "part_of_speech": "n", "pronunciation": "/ɡlɑːs/"},
    {"en": "government building", "ru": "государственное здание", "part_of_speech": "n", "pronunciation": "/ˈɡʌvənmənt ˈbɪldɪŋ/"},
    {"en": "grow", "ru": "расти", "part_of_speech": "v", "pronunciation": "/ɡrəʊ/"},
    {"en": "guest", "ru": "гость", "part_of_speech": "n", "pronunciation": "/ɡest/"},
    {"en": "in", "ru": "в", "part_of_speech": "prep", "pronunciation": "/ɪn/"},
    {"en": "jogging track", "ru": "беговая дорожка", "part_of_speech": "n", "pronunciation": "/ˈdʒɒɡɪŋ træk/"},
    {"en": "kettle", "ru": "чайник", "part_of_speech": "n", "pronunciation": "/ˈketl/"},
    {"en": "keys", "ru": "ключи", "part_of_speech": "pl n", "pronunciation": "/kiːz/"},
    {"en": "kitchen", "ru": "кухня", "part_of_speech": "n", "pronunciation": "/ˈkɪtʃɪn/"},
    {"en": "lamp", "ru": "лампа", "part_of_speech": "n", "pronunciation": "/læmp/"},
    {"en": "library", "ru": "библиотека", "part_of_speech": "n", "pronunciation": "/ˈlaɪbri/"},
    {"en": "lipstick", "ru": "помада", "part_of_speech": "n", "pronunciation": "/ˈlɪpstɪk/"},
    {"en": "living room", "ru": "гостиная", "part_of_speech": "n", "pronunciation": "/ˈlɪvɪŋ ruːm/"},
    {"en": "mirror", "ru": "зеркало", "part_of_speech": "n", "pronunciation": "/ˈmɪrə(r)/"},
    {"en": "movie theater", "ru": "кинотеатр", "part_of_speech": "n", "pronunciation": "/ˈmuːvi ˈθɪətə(r)/"},
    {"en": "mug", "ru": "кружка", "part_of_speech": "n", "pronunciation": "/mʌg/"},
    {"en": "next to", "ru": "рядом с", "part_of_speech": "prep", "pronunciation": "/ˈnekst tuː/"},
    {"en": "on", "ru": "на", "part_of_speech": "prep", "pronunciation": "/ɒn/"},
    {"en": "opposite", "ru": "напротив", "part_of_speech": "prep", "pronunciation": "/ˈɒpəzɪt/"},
    {"en": "outside", "ru": "снаружи", "part_of_speech": "prep", "pronunciation": "/ˌaʊtˈsaɪd/"},
    {"en": "oven", "ru": "духовка", "part_of_speech": "n", "pronunciation": "/ˈʌvn/"},
    {"en": "party", "ru": "вечеринка", "part_of_speech": "n", "pronunciation": "/ˈpɑːti/"},
    {"en": "pavement", "ru": "тротуар", "part_of_speech": "n", "pronunciation": "/ˈpeɪvmənt/"},
    {"en": "pen", "ru": "ручка", "part_of_speech": "n", "pronunciation": "/pen/"},
    {"en": "phone", "ru": "телефон", "part_of_speech": "n", "pronunciation": "/fəʊn/"},
    {"en": "picture", "ru": "картина", "part_of_speech": "n", "pronunciation": "/ˈpɪktʃə(r)/"},
    {"en": "plate", "ru": "тарелка", "part_of_speech": "n", "pronunciation": "/pleɪt/"},
    {"en": "post office", "ru": "почта", "part_of_speech": "n", "pronunciation": "/ˈpəʊst ˌɒfɪs/"},
    {"en": "president", "ru": "президент", "part_of_speech": "n", "pronunciation": "/ˈprezɪdənt/"},
    {"en": "public", "ru": "общественность", "part_of_speech": "n", "pronunciation": "/ˈpʌblɪk/"},
    {"en": "purse", "ru": "кошелек женский", "part_of_speech": "n", "pronunciation": "/pɜːs/"},
    {"en": "relax", "ru": "расслабляться", "part_of_speech": "v", "pronunciation": "/rɪˈlæks/"},
    {"en": "rent", "ru": "снимать (жильё)", "part_of_speech": "v", "pronunciation": "/rent/"},
    {"en": "shoes", "ru": "туфли", "part_of_speech": "pl n", "pronunciation": "/ʃuːz/"},
    {"en": "shower", "ru": "душ", "part_of_speech": "n", "pronunciation": "/ˈʃaʊə(r)/"},
    {"en": "sleep", "ru": "спать", "part_of_speech": "v", "pronunciation": "/sliːp/"},
    {"en": "sofa", "ru": "диван", "part_of_speech": "n", "pronunciation": "/ˈsəʊfə/"},
    {"en": "swimming pool", "ru": "бассейн", "part_of_speech": "n", "pronunciation": "/ˈswɪmɪŋ puːl/"},
    {"en": "table", "ru": "стол", "part_of_speech": "n", "pronunciation": "/ˈteɪbl/"},
    {"en": "tennis court", "ru": "теннисный корт", "part_of_speech": "n", "pronunciation": "/ˈtenɪs kɔːt/"},
    {"en": "terrible", "ru": "ужасный", "part_of_speech": "adj", "pronunciation": "/ˈterəbl/"},
    {"en": "third floor", "ru": "третий этаж", "part_of_speech": "n", "pronunciation": "/θɜːd flɔː(r)/"},
    {"en": "towel", "ru": "полотенце", "part_of_speech": "n", "pronunciation": "/ˈtaʊəl/"},
    {"en": "tree", "ru": "дерево", "part_of_speech": "n", "pronunciation": "/triː/"},
    {"en": "under", "ru": "под", "part_of_speech": "prep", "pronunciation": "/ˈʌndə(r)/"},
    {"en": "unfortunately", "ru": "к сожалению, к несчастью", "part_of_speech": "adv", "pronunciation": "/ʌnˈfɔːtʃənətli/"},
    {"en": "vegetables", "ru": "овощи", "part_of_speech": "pl n", "pronunciation": "/ˈvedʒtəblz/"},
    {"en": "visitor", "ru": "посетитель", "part_of_speech": "n", "pronunciation": "/ˈvɪzɪtə(r)/"},
    {"en": "wall", "ru": "стена", "part_of_speech": "n", "pronunciation": "/wɔːl/"},
    {"en": "wallet", "ru": "кошелек", "part_of_speech": "n", "pronunciation": "/ˈwɒlɪt/"},
    {"en": "washing machine", "ru": "стиральная машина", "part_of_speech": "n", "pronunciation": "/ˈwɒʃɪŋ məʃiːn/"},
    {"en": "wedding", "ru": "свадьба", "part_of_speech": "n", "pronunciation": "/ˈwedɪŋ/"},
    {"en": "window", "ru": "окно", "part_of_speech": "n", "pronunciation": "/ˈwɪndəʊ/"},
    {"en": "wine", "ru": "вино", "part_of_speech": "n", "pronunciation": "/waɪn/"},
    {"en": "wing", "ru": "крыло", "part_of_speech": "n", "pronunciation": "/wɪŋ/"},
    {"en": "wonderful", "ru": "прекрасный, чудесный", "part_of_speech": "adj", "pronunciation": "/ˈwʌndəfl/"},
    {"en": "world-famous", "ru": "мировой известности", "part_of_speech": "adj", "pronunciation": "/ˌwɜːld ˈfeɪməs/"}
]