const unit06 = [
    {"en": "advice", "ru": "совет", "part_of_speech": "n", "pronunciation": "/ədˈvaɪs/"},
    {"en": "again", "ru": "снова", "part_of_speech": "adv", "pronunciation": "/əˈɡeɪn/"},
    {"en": "annoyed", "ru": "раздражённый", "part_of_speech": "adj", "pronunciation": "/əˈnɔɪd/"},
    {"en": "any more", "ru": "больше", "part_of_speech": "adv", "pronunciation": "/eni ˈmɔː/"},
    {"en": "arrive", "ru": "прибывать", "part_of_speech": "v", "pronunciation": "/əˈraɪv/"},
    {"en": "artistic", "ru": "художественный", "part_of_speech": "adj", "pronunciation": "/ɑːˈtɪstɪk/"},
    {"en": "ask", "ru": "спрашивать", "part_of_speech": "v", "pronunciation": "/ɑːsk/"},
    {"en": "award", "ru": "награда", "part_of_speech": "n", "pronunciation": "/əˈwɔːd/"},
    {"en": "before", "ru": "до", "part_of_speech": "prep", "pronunciation": "/bɪˈfɔː(r)/"},
    {"en": "begin", "ru": "начинать", "part_of_speech": "v", "pronunciation": "/bɪˈɡɪn/"},
    {"en": "behaviour", "ru": "поведение", "part_of_speech": "n", "pronunciation": "/bɪˈheɪvjə(r)/"},
    {"en": "best friend", "ru": "лучший друг", "part_of_speech": "n", "pronunciation": "/best frend/"},
    {"en": "billionaire", "ru": "миллиардер", "part_of_speech": "n", "pronunciation": "/ˌbɪljəˈneə(r)/"},
    {"en": "boat", "ru": "лодка", "part_of_speech": "n", "pronunciation": "/bəʊt/"},
    {"en": "bored", "ru": "скучающий", "part_of_speech": "adj", "pronunciation": "/bɔːd/"},
    {"en": "born", "ru": "родится, рождаться", "part_of_speech": "v pp", "pronunciation": "/bɔːn/"},
    {"en": "breakfast", "ru": "завтрак", "part_of_speech": "n", "pronunciation": "/ˈbrekfəst/"},
    {"en": "businessman", "ru": "бизнесмен", "part_of_speech": "n", "pronunciation": "/ˈbɪznəsmən/"},
    {"en": "catch", "ru": "ловить", "part_of_speech": "v", "pronunciation": "/kætʃ/"},
    {"en": "century", "ru": "век", "part_of_speech": "n", "pronunciation": "/ˈsentʃəri/"},
    {"en": "charity", "ru": "благотворительность", "part_of_speech": "n", "pronunciation": "/ˈtʃærəti/"},
    {"en": "childhood", "ru": "детство", "part_of_speech": "n", "pronunciation": "/ˈtʃaɪldhʊd/"},
    {"en": "Christmas", "ru": "Рождество", "part_of_speech": "n", "pronunciation": "/ˈkrɪsməs/"},
    {"en": "clean", "ru": "чистить", "part_of_speech": "v", "pronunciation": "/kliːn/"},
    {"en": "clever", "ru": "умный", "part_of_speech": "adj", "pronunciation": "/ˈklevə(r)/"},
    {"en": "coal mine", "ru": "угольная шахта", "part_of_speech": "n", "pronunciation": "/ˈkəʊl maɪn/"},
    {"en": "company", "ru": "компания", "part_of_speech": "n", "pronunciation": "/ˈkʌmpəni/"},
    {"en": "dad", "ru": "папа", "part_of_speech": "n", "pronunciation": "/dæd/"},
    {"en": "date", "ru": "дата", "part_of_speech": "n", "pronunciation": "/deɪt/"},
    {"en": "daughters", "ru": "дочери", "part_of_speech": "pl n", "pronunciation": "/ˈdɔːtəz/"},
    {"en": "designer", "ru": "дизайнер", "part_of_speech": "n", "pronunciation": "/dɪˈzaɪnə(r)/"},
    {"en": "die", "ru": "умереть", "part_of_speech": "v", "pronunciation": "/daɪ/"},
    {"en": "dollars", "ru": "доллары", "part_of_speech": "pl n", "pronunciation": "/ˈdɒləz/"},
    {"en": "drama", "ru": "драма", "part_of_speech": "n", "pronunciation": "/ˈdrɑːmə/"},
    {"en": "dyslexic", "ru": "дислексия", "part_of_speech": "adj", "pronunciation": "/dɪsˈleksɪk/"},
    {"en": "emails", "ru": "электронные письма", "part_of_speech": "pl n", "pronunciation": "/ˈiːmeɪlz/"},
    {"en": "enough", "ru": "достаточно", "part_of_speech": "adv", "pronunciation": "/ɪˈnʌf/"},
    {"en": "entrepreneur", "ru": "предприниматель", "part_of_speech": "n", "pronunciation": "/ˌɒntrəprəˈnɜː(r)/"},
    {"en": "everything", "ru": "все", "part_of_speech": "pron", "pronunciation": "/ˈevriθɪŋ/"},
    {"en": "everywhere", "ru": "везде", "part_of_speech": "adv", "pronunciation": "/ˈevriweə(r)/"},
    {"en": "exam", "ru": "экзамен", "part_of_speech": "n", "pronunciation": "/ɪɡˈzæm/"},
    {"en": "excited", "ru": "взволнованный", "part_of_speech": "adj", "pronunciation": "/ɪkˈsaɪtɪd/"},
    {"en": "exclaim", "ru": "воскликнуть", "part_of_speech": "v", "pronunciation": "/ɪkˈskleɪm/"},
    {"en": "export", "ru": "экспортировать", "part_of_speech": "v", "pronunciation": "/ekˈspɔːt/"},
    {"en": "fashion show", "ru": "модное шоу", "part_of_speech": "n", "pronunciation": "/ˈfæʃn ʃəʊ/"},
    {"en": "film", "ru": "фильм", "part_of_speech": "n", "pronunciation": "/fɪlm/"},
    {"en": "first", "ru": "первый", "part_of_speech": "adj", "pronunciation": "/fɜːst/"},
    {"en": "fish", "ru": "рыба", "part_of_speech": "n", "pronunciation": "/fɪʃ/"},
    {"en": "fisherman", "ru": "рыбак", "part_of_speech": "n", "pronunciation": "/ˈfɪʃəmən/"},
    {"en": "football team", "ru": "футбольная команда", "part_of_speech": "n", "pronunciation": "/ˈfʊtbɔːl tiːm/"},
    {"en": "friend", "ru": "друг", "part_of_speech": "n", "pronunciation": "/frend/"},
    {"en": "full", "ru": "полный", "part_of_speech": "adj", "pronunciation": "/fʊl/"},
    {"en": "funny", "ru": "смешной", "part_of_speech": "adj", "pronunciation": "/ˈfʌni/"},
    {"en": "gentleman", "ru": "джентльмен", "part_of_speech": "n", "pronunciation": "/ˈdʒentlmən/"},
    {"en": "give", "ru": "давать", "part_of_speech": "v", "pronunciation": "/ɡɪv/"},
    {"en": "great-grandparents", "ru": "прадедушки и прабабушки", "part_of_speech": "pl n", "pronunciation": "/ɡreɪt/"},
    {"en": "help", "ru": "помогать", "part_of_speech": "v", "pronunciation": "/help/"},
    {"en": "interview", "ru": "интервью", "part_of_speech": "v", "pronunciation": "/ˈɪntəvjuː/"},
    {"en": "last night", "ru": "прошлой ночью", "part_of_speech": "n", "pronunciation": "/lɑːst naɪt/"},
    {"en": "last year", "ru": "прошлый год", "part_of_speech": "n", "pronunciation": "/lɑːst jɜː(r)/"},
    {"en": "late", "ru": "поздний", "part_of_speech": "adj", "pronunciation": "/leɪt/"},
    {"en": "laugh", "ru": "смеяться", "part_of_speech": "v", "pronunciation": "/lɑːf/"},
    {"en": "leave", "ru": "уходить", "part_of_speech": "v", "pronunciation": "/liːv/"},
    {"en": "lecture", "ru": "лекция", "part_of_speech": "n", "pronunciation": "/ˈlektʃə(r)/"},
    {"en": "local", "ru": "местный", "part_of_speech": "adj", "pronunciation": "/ˈləʊkl/"},
    {"en": "longer", "ru": "дольше", "part_of_speech": "adj", "pronunciation": "/ˈlɒŋɡə(r)/"},
    {"en": "lose", "ru": "терять", "part_of_speech": "v", "pronunciation": "/luːz/"},
    {"en": "lottery", "ru": "лотерея", "part_of_speech": "n", "pronunciation": "/ˈlɒtəri/"},
    {"en": "lots (of sth)", "ru": "много (чего-либо)", "part_of_speech": "pl n", "pronunciation": "/lɒts/"},
    {"en": "make", "ru": "делать", "part_of_speech": "v", "pronunciation": "/meɪk/"},
    {"en": "marathon", "ru": "марафон", "part_of_speech": "n", "pronunciation": "/ˈmærəθən/"},
    {"en": "match", "ru": "матч", "part_of_speech": "n", "pronunciation": "/mætʃ/"},
    {"en": "matter", "ru": "иметь значение", "part_of_speech": "v", "pronunciation": "/ˈmætə(r)/"},
    {"en": "millionaire", "ru": "миллионер", "part_of_speech": "n", "pronunciation": "/ˌmɪljəˈneə(r)/"},
    {"en": "minutes", "ru": "минуты", "part_of_speech": "pl n", "pronunciation": "/ˈmɪnɪts/"},
    {"en": "month", "ru": "месяц", "part_of_speech": "n", "pronunciation": "/mʌnθ/"},
    {"en": "move", "ru": "двигаться", "part_of_speech": "v", "pronunciation": "/muːv/"},
    {"en": "much", "ru": "много", "part_of_speech": "det", "pronunciation": "/mʌtʃ/"},
    {"en": "nationality", "ru": "национальность", "part_of_speech": "n", "pronunciation": "/ˌnæʃəˈnæləti/"},
    {"en": "news", "ru": "новости", "part_of_speech": "n", "pronunciation": "/njuːz/"},
    {"en": "nothing", "ru": "ничего", "part_of_speech": "pron", "pronunciation": "/ˈnʌθɪŋ/"},
    {"en": "present", "ru": "подарок", "part_of_speech": "n", "pronunciation": "/ˈpreznt/"},
    {"en": "problems", "ru": "проблемы", "part_of_speech": "pl n", "pronunciation": "/ˈprɒbləmz/"},
    {"en": "radio station", "ru": "радиостанция", "part_of_speech": "n", "pronunciation": "/ˈreɪdiəʊ ˈsteɪʃn/"},
    {"en": "receive", "ru": "получать", "part_of_speech": "v", "pronunciation": "/rɪˈsiːv/"},
    {"en": "richest", "ru": "самый богатый, богатейший", "part_of_speech": "adj", "pronunciation": "/ˈrɪtʃɪst/"},
    {"en": "run a company", "ru": "управлять компанией", "part_of_speech": "v", "pronunciation": "/rʌn ə kʌmpəni/"},
    {"en": "scholarship", "ru": "ученость", "part_of_speech": "n", "pronunciation": "/ˈskɒləʃɪp/"},
    {"en": "siesta", "ru": "сиеста", "part_of_speech": "n", "pronunciation": "/siˈestə/"},
    {"en": "software", "ru": "программное обеспечение", "part_of_speech": "n", "pronunciation": "/ˈsɒftweə(r)/"},
    {"en": "start", "ru": "начинать", "part_of_speech": "v", "pronunciation": "/stɑːt/"},
    {"en": "stay in touch", "ru": "оставаться на связи", "part_of_speech": "v", "pronunciation": "/steɪ ɪn tʌtʃ/"},
    {"en": "successful", "ru": "успешный", "part_of_speech": "adj", "pronunciation": "/səkˈsesfl/"},
    {"en": "talk show", "ru": "ток-шоу", "part_of_speech": "n", "pronunciation": "/ˈtɔːk ʃəʊ/"},
    {"en": "toast", "ru": "тост", "part_of_speech": "n", "pronunciation": "/təʊst/"},
    {"en": "tomorrow", "ru": "завтра", "part_of_speech": "adv", "pronunciation": "/təˈmɒrəʊ/"},
    {"en": "TV star", "ru": "телезвезда", "part_of_speech": "n", "pronunciation": "/ˌtiː ˈviː stɑː(r)/"},
    {"en": "Valentine’s Day", "ru": "День Святого Валентина", "part_of_speech": "n", "pronunciation": "/ˈvæləntaɪnz deɪ/"},
    {"en": "watch", "ru": "смотреть", "part_of_speech": "v", "pronunciation": "/wɒtʃ/"},
    {"en": "win", "ru": "выигрывать", "part_of_speech": "v", "pronunciation": "/wɪn/"},
    {"en": "women", "ru": "женщины", "part_of_speech": "pl n", "pronunciation": "/ˈwɪmɪn/"},
    {"en": "word", "ru": "слово", "part_of_speech": "n", "pronunciation": "/wɜːd/"},
    {"en": "worried", "ru": "взволнованный", "part_of_speech": "adj", "pronunciation": "/ˈwʌrid/"},
    {"en": "yesterday", "ru": "вчера", "part_of_speech": "n", "pronunciation": "/ˈjestədeɪ/"}
]