const unit11 = [
    {"en": "backpack", "ru": "рюкзак", "part_of_speech": "n", "pronunciation": "/ˈbækpæk/"},
    {"en": "carry", "ru": "нести", "part_of_speech": "v", "pronunciation": "/ˈkæri/"},
    {"en": "climb", "ru": "взбираться", "part_of_speech": "v", "pronunciation": "/klaɪm/"},
    {"en": "colourful", "ru": "яркий, разноцветный, красочный", "part_of_speech": "adj", "pronunciation": "/ˈkʌləfl/"},
    {"en": "cruise", "ru": "круиз", "part_of_speech": "n", "pronunciation": "/kruːz/"},
    {"en": "do the washing", "ru": "заняться стиркой", "part_of_speech": "v", "pronunciation": "/duː ðə ˈwɒʃɪŋ/"},
    {"en": "drop", "ru": "ронять, бросать", "part_of_speech": "v", "pronunciation": "/drɒp/"},
    {"en": "due", "ru": "надлежащий,ожидаемый", "part_of_speech": "adj", "pronunciation": "/djuː/"},
    {"en": "fall", "ru": "падать", "part_of_speech": "v", "pronunciation": "/fɔːl/"},
    {"en": "fields", "ru": "поля", "part_of_speech": "pl n", "pronunciation": "/fiːldz/"},
    {"en": "folk song", "ru": "народная песня", "part_of_speech": "n", "pronunciation": "/ˈfəʊk sɒŋ/"},
    {"en": "freedom", "ru": "свобода", "part_of_speech": "n", "pronunciation": "/ˈfriːdəm/"},
    {"en": "frightened", "ru": "испуганный", "part_of_speech": "adj", "pronunciation": "/ˈfraɪtnd/"},
    {"en": "future", "ru": "будущее", "part_of_speech": "n", "pronunciation": "/ˈfjuːtʃə(r)/"},
    {"en": "grow up", "ru": "расти, взрослеть", "part_of_speech": "v", "pronunciation": "/ɡrəʊ ˈʌp/"},
    {"en": "harmony", "ru": "гармония", "part_of_speech": "n", "pronunciation": "/ˈhɑːməni/"},
    {"en": "hat", "ru": "шляпа", "part_of_speech": "n", "pronunciation": "/hæt/"},
    {"en": "hire", "ru": "нанимать", "part_of_speech": "v", "pronunciation": "/ˈhaɪə(r)/"},
    {"en": "hospitality", "ru": "гостеприимство", "part_of_speech": "n", "pronunciation": "/ˌhɒspɪˈtæləti/"},
    {"en": "human", "ru": "человек", "part_of_speech": "adj", "pronunciation": "/ˈhjuːmən/"},
    {"en": "jacket", "ru": "куртка", "part_of_speech": "n", "pronunciation": "/ˈdʒækɪt/"},
    {"en": "kiss", "ru": "целовать, поцеловать", "part_of_speech": "v", "pronunciation": "/kɪs/"},
    {"en": "passers-by", "ru": "прохожие", "part_of_speech": "pl n", "pronunciation": "/ˌpɑːsəz ˈbaɪ/"},
    {"en": "pay rise", "ru": "повышение зарплаты", "part_of_speech": "n", "pronunciation": "/ˈpeɪ raɪz/"},
    {"en": "peaceful", "ru": "мирный", "part_of_speech": "adj", "pronunciation": "/ˈpiːsfl/"},
    {"en": "perfect", "ru": "идеальный, совершенный", "part_of_speech": "adj", "pronunciation": "/ˈpɜːfɪkt/"},
    {"en": "picnic", "ru": "пикник", "part_of_speech": "n", "pronunciation": "/ˈpɪknɪk/"},
    {"en": "plan", "ru": "планировать", "part_of_speech": "v", "pronunciation": "/plæn/"},
    {"en": "podcasts", "ru": "подкасты", "part_of_speech": "pl n", "pronunciation": "/ˈpɒdkɑːsts/"},
    {"en": "pyramids", "ru": "пирамиды", "part_of_speech": "pl n", "pronunciation": "/ˈpɪrəmɪdz/"},
    {"en": "retire", "ru": "уходить в отставку/пенсию", "part_of_speech": "v", "pronunciation": "/rɪˈtaɪə(r)/"},
    {"en": "safari", "ru": "сафари", "part_of_speech": "n", "pronunciation": "/səˈfɑːri/"},
    {"en": "sign", "ru": "знак", "part_of_speech": "n", "pronunciation": "/saɪn/"},
    {"en": "simple", "ru": "простой", "part_of_speech": "adj", "pronunciation": "/ˈsɪmpl/"},
    {"en": "smile", "ru": "улыбаться", "part_of_speech": "v", "pronunciation": "/smaɪl/"},
    {"en": "sneeze", "ru": "чихать", "part_of_speech": "v", "pronunciation": "/sniːz/"},
    {"en": "soon", "ru": "скоро", "part_of_speech": "adv", "pronunciation": "/suːn/"},
    {"en": "storm", "ru": "буря", "part_of_speech": "n", "pronunciation": "/stɔːm/"},
    {"en": "stressful", "ru": "стрессовый", "part_of_speech": "adj", "pronunciation": "/ˈstresfl/"},
    {"en": "suitcase", "ru": "чемодан", "part_of_speech": "n", "pronunciation": "/ˈsuːtkeɪs/"},
    {"en": "supper", "ru": "ужин", "part_of_speech": "n", "pronunciation": "/ˈsʌpə(r)/"},
    {"en": "thunder", "ru": "гроза", "part_of_speech": "n", "pronunciation": "/ˈθʌndə(r)/"},
    {"en": "Wales", "ru": "Уэльс", "part_of_speech": "n", "pronunciation": "/weɪlz/"},
    {"en": "walking stick", "ru": "трость для ходьбы", "part_of_speech": "n", "pronunciation": "/ˈwɔːkɪŋ stɪk/"},
    {"en": "website", "ru": "вебсайт", "part_of_speech": "n", "pronunciation": "/ˈwebsaɪt/"},
    {"en": "woods", "ru": "лес", "part_of_speech": "pl n", "pronunciation": "/wʊdz/"}
]