const unit08 = [
    {"en": "adaptor", "ru": "переходник, адаптер", "part_of_speech": "n", "pronunciation": "/əˈdæptə(r)/"},
    {"en": "add", "ru": "добавлять", "part_of_speech": "v", "pronunciation": "/æd/"},
    {"en": "any", "ru": "любой", "part_of_speech": "det", "pronunciation": "/ˈeni/"},
    {"en": "apple", "ru": "яблоко", "part_of_speech": "n", "pronunciation": "/ˈæpl/"},
    {"en": "apple juice", "ru": "яблочный сок", "part_of_speech": "n", "pronunciation": "/ˈæpl  dʒuːs/"},
    {"en": "aspirin", "ru": "аспирин", "part_of_speech": "n", "pronunciation": "/ˈæsprɪn/"},
    {"en": "bacon", "ru": "бекон", "part_of_speech": "n", "pronunciation": "/ˈbeɪkən/"},
    {"en": "banana", "ru": "банан", "part_of_speech": "n", "pronunciation": "/bəˈnɑːnə/"},
    {"en": "basil", "ru": "базилик", "part_of_speech": "n", "pronunciation": "/ˈbæzl/"},
    {"en": "batteries", "ru": "батареи", "part_of_speech": "pl n", "pronunciation": "/ˈbætəriz/"},
    {"en": "beef", "ru": "говядина", "part_of_speech": "n", "pronunciation": "/biːf/"},
    {"en": "biscuits", "ru": "печенье", "part_of_speech": "pl n", "pronunciation": "/ˈbɪskɪts/"},
    {"en": "boil", "ru": "кипятить", "part_of_speech": "v", "pronunciation": "/bɔɪl/"},
    {"en": "boring", "ru": "скучный", "part_of_speech": "adj", "pronunciation": "/ˈbɔːrɪŋ/"},
    {"en": "bread", "ru": "хлеб", "part_of_speech": "n", "pronunciation": "/bred/"},
    {"en": "broccoli", "ru": "брокколи", "part_of_speech": "n", "pronunciation": "/ˈbrɒkəli/"},
    {"en": "butter", "ru": "масло", "part_of_speech": "n", "pronunciation": "/ˈbʌtə(r)/"},
    {"en": "carrots", "ru": "морковь", "part_of_speech": "pl n", "pronunciation": "/ˈkærəts/"},
    {"en": "cartoon characters", "ru": "персонажи мультфильмов", "part_of_speech": "pl n", "pronunciation": "/kɑːˈtuːn ˈkærəktəz/"},
    {"en": "cats", "ru": "кошки", "part_of_speech": "pl n", "pronunciation": "/kæts/"},
    {"en": "chef", "ru": "повар", "part_of_speech": "n", "pronunciation": "/ʃef/"},
    {"en": "chips", "ru": "чипсы", "part_of_speech": "pl n", "pronunciation": "/tʃɪps/"},
    {"en": "chocolate", "ru": "шоколад", "part_of_speech": "n", "pronunciation": "/ˈtʃɒklət/"},
    {"en": "chop", "ru": "рубить", "part_of_speech": "v", "pronunciation": "/tʃɒp/"},
    {"en": "club", "ru": "клуб", "part_of_speech": "n", "pronunciation": "/klʌb/"},
    {"en": "coach", "ru": "тренер", "part_of_speech": "n", "pronunciation": "/kəʊtʃ/"},
    {"en": "cold drink", "ru": "холодный напиток", "part_of_speech": "n", "pronunciation": "/kəʊld  drɪŋk/"},
    {"en": "cookbook", "ru": "книга рецептов", "part_of_speech": "n", "pronunciation": "/ˈkʊkbʊk/"},
    {"en": "cooking", "ru": "готовка", "part_of_speech": "n", "pronunciation": "/ˈkʊkɪŋ/"},
    {"en": "cottage pie", "ru": "творожный пирог", "part_of_speech": "n", "pronunciation": "/ˌkɒtɪdʒ ˈpaɪ/"},
    {"en": "crisps", "ru": "чипсы", "part_of_speech": "pl n", "pronunciation": "/krɪsps/"},
    {"en": "croissant", "ru": "круассан", "part_of_speech": "n", "pronunciation": "/ˈkrwæsɒ̃/"},
    {"en": "daily", "ru": "ежедневный", "part_of_speech": "adj", "pronunciation": "/ˈdeɪli/"},
    {"en": "delicious", "ru": "вкусный", "part_of_speech": "adj", "pronunciation": "/dɪˈlɪʃəs/"},
    {"en": "disgusting", "ru": "отвратительный", "part_of_speech": "adj", "pronunciation": "/dɪsˈɡʌstɪŋ/"},
    {"en": "dry", "ru": "сухой", "part_of_speech": "adj", "pronunciation": "/draɪ/"},
    {"en": "eggs", "ru": "яйца", "part_of_speech": "pl n", "pronunciation": "/eɡz/"},
    {"en": "envelopes", "ru": "конверты", "part_of_speech": "pl n", "pronunciation": "/ˈenvələʊps/"},
    {"en": "especially", "ru": "особенно", "part_of_speech": "adv", "pronunciation": "/ɪˈspeʃəli/"},
    {"en": "fashionable", "ru": "модный", "part_of_speech": "adj", "pronunciation": "/ˈfæʃnəbl/"},
    {"en": "favourite", "ru": "любимый", "part_of_speech": "adj", "pronunciation": "/ˈfeɪvərɪt/"},
    {"en": "fish fingers", "ru": "рыбные палочки", "part_of_speech": "pl n", "pronunciation": "/ˌfɪʃ  ˈfɪŋɡəz/"},
    {"en": "forget", "ru": "забывать", "part_of_speech": "v", "pronunciation": "/fəˈɡet/"},
    {"en": "fry", "ru": "жарить", "part_of_speech": "v", "pronunciation": "/fraɪ/"},
    {"en": "fussy", "ru": "суетливый", "part_of_speech": "adj", "pronunciation": "/ˈfʌsi/"},
    {"en": "gamble", "ru": "рисковать (азартные игры)", "part_of_speech": "v", "pronunciation": "/ˈɡæmbl/"},
    {"en": "grams", "ru": "граммы", "part_of_speech": "pl n", "pronunciation": "/ɡræmz/"},
    {"en": "ham", "ru": "ветчина", "part_of_speech": "n", "pronunciation": "/hæm/"},
    {"en": "hardware shop", "ru": "хозяйственный магазин", "part_of_speech": "n", "pronunciation": "/ˈhɑːdweə(r) ʃɒp/"},
    {"en": "herbs", "ru": "травы", "part_of_speech": "pl n", "pronunciation": "/hɜːbz/"},
    {"en": "honey", "ru": "мед", "part_of_speech": "n", "pronunciation": "/ˈhʌni/"},
    {"en": "how much", "ru": "сколько", "part_of_speech": "phr", "pronunciation": "/haʊ  mʌtʃ/"},
    {"en": "hungry", "ru": "голодный", "part_of_speech": "adj", "pronunciation": "/ˈhʌŋɡri/"},
    {"en": "I’m afraid", "ru": "я боюсь", "part_of_speech": "phr", "pronunciation": "/aɪm  əˈfreɪd/"},
    {"en": "ingredient", "ru": "ингредиент", "part_of_speech": "n", "pronunciation": "/ɪnˈɡriːdiənt/"},
    {"en": "kid", "ru": "ребенок", "part_of_speech": "n", "pronunciation": "/kɪd/"},
    {"en": "large", "ru": "большой", "part_of_speech": "adj", "pronunciation": "/lɑːdʒ/"},
    {"en": "layer", "ru": "слой", "part_of_speech": "n", "pronunciation": "/ˈleɪə(r)/"},
    {"en": "list", "ru": "список", "part_of_speech": "n", "pronunciation": "/lɪst/"},
    {"en": "magazine", "ru": "журнал", "part_of_speech": "n", "pronunciation": "/ˌmæɡəˈziːn/"},
    {"en": "meat", "ru": "мясо", "part_of_speech": "n", "pronunciation": "/miːt/"},
    {"en": "medium", "ru": "средний", "part_of_speech": "adj", "pronunciation": "/ˈmiːdiəm/"},
    {"en": "milk", "ru": "молоко", "part_of_speech": "n", "pronunciation": "/mɪlk/"},
    {"en": "minced", "ru": "рубленный, измельченный", "part_of_speech": "adj", "pronunciation": "/mɪnst/"},
    {"en": "miss", "ru": "скучать", "part_of_speech": "v", "pronunciation": "/mɪs/"},
    {"en": "mix", "ru": "смешивать", "part_of_speech": "v", "pronunciation": "/mɪks/"},
    {"en": "mustard", "ru": "горчица", "part_of_speech": "n", "pronunciation": "/ˈmʌstəd/"},
    {"en": "need", "ru": "нуждаться", "part_of_speech": "v", "pronunciation": "/niːd/"},
    {"en": "newsagent’s", "ru": "магазин прессы", "part_of_speech": "n", "pronunciation": "/ˈnjuːzeɪdʒənts/"},
    {"en": "no problem", "ru": "без проблем", "part_of_speech": "phr", "pronunciation": "/nəʊ  ˈprɒbləm/"},
    {"en": "notebook", "ru": "блокнот", "part_of_speech": "n", "pronunciation": "/ˈnəʊtbʊk/"},
    {"en": "nuts", "ru": "орехи", "part_of_speech": "pl n", "pronunciation": "/nʌts/"},
    {"en": "oil", "ru": "масло", "part_of_speech": "n", "pronunciation": "/ɔɪl/"},
    {"en": "olives", "ru": "оливки", "part_of_speech": "pl n", "pronunciation": "/ˈɒlɪvz/"},
    {"en": "onions", "ru": "лук", "part_of_speech": "pl n", "pronunciation": "/ˈʌnjənz/"},
    {"en": "order", "ru": "заказать", "part_of_speech": "v", "pronunciation": "/ˈɔːdə(r)/"},
    {"en": "out", "ru": "снаруже, за пределами", "part_of_speech": "prep", "pronunciation": "/aʊt/"},
    {"en": "thyme", "ru": "тимьян", "part_of_speech": "n", "pronunciation": "/taɪm/"},
    {"en": "tomatoes", "ru": "помидоры", "part_of_speech": "pl n", "pronunciation": "/təˈmɑːtəʊz/"},
    {"en": "toothpaste", "ru": "зубная паста", "part_of_speech": "n", "pronunciation": "/ˈtuːθpeɪst/"},
    {"en": "try", "ru": "пытаться, попробовать", "part_of_speech": "v", "pronunciation": "/traɪ/"},
    {"en": "until", "ru": "до", "part_of_speech": "prep", "pronunciation": "/ənˈtɪl/"},
    {"en": "waitress", "ru": "официантка", "part_of_speech": "n", "pronunciation": "/ˈweɪtrəs/"},
    {"en": "worldwide", "ru": "по всему миру, мировой", "part_of_speech": "adj", "pronunciation": "/ˈwɜːldwaɪd/"},
    {"en": "worry", "ru": "беспокоиться", "part_of_speech": "v", "pronunciation": "/ˈwʌri/"},
    {"en": "yoghurt", "ru": "йогурт", "part_of_speech": "n", "pronunciation": "/ˈjɒɡət/"},
    {"en": "packet", "ru": "пакет", "part_of_speech": "n", "pronunciation": "/ˈpækɪt/"},
    {"en": "pasta", "ru": "паста", "part_of_speech": "n", "pronunciation": "/ˈpæstə/"},
    {"en": "peanut butter", "ru": "арахисовое масло", "part_of_speech": "n", "pronunciation": "/ˌpiːnʌt  ˈbʌtə(r)/"},
    {"en": "peas", "ru": "горох", "part_of_speech": "pl n", "pronunciation": "/piːz/"},
    {"en": "pepper", "ru": "перец", "part_of_speech": "n", "pronunciation": "/ˈpepə(r)/"},
    {"en": "plasters", "ru": "пластыри", "part_of_speech": "pl n", "pronunciation": "/ˈplɑːstəz/"},
    {"en": "pocket", "ru": "карман", "part_of_speech": "n", "pronunciation": "/ˈpɒkɪt/"},
    {"en": "popular", "ru": "популярный", "part_of_speech": "adj", "pronunciation": "/ˈpɒpjələ(r)/"},
    {"en": "potatoes", "ru": "картофель", "part_of_speech": "pl n", "pronunciation": "/pəˈteɪtəʊz/"},
    {"en": "raspberry", "ru": "малина", "part_of_speech": "n", "pronunciation": "/ˈrɑːzbəri/"},
    {"en": "recipe", "ru": "рецепт", "part_of_speech": "n", "pronunciation": "/ˈresəpi/"},
    {"en": "record", "ru": "запись", "part_of_speech": "v", "pronunciation": "/rɪˈkɔːd/"},
    {"en": "salad", "ru": "салат", "part_of_speech": "n", "pronunciation": "/ˈsæləd/"},
    {"en": "salt", "ru": "соль", "part_of_speech": "n", "pronunciation": "/sɒlt/"},
    {"en": "scissors", "ru": "ножницы", "part_of_speech": "pl n", "pronunciation": "/ˈsɪzəz/"},
    {"en": "screwdriver", "ru": "отвертка", "part_of_speech": "n", "pronunciation": "/ˈskruːdraɪvə(r)/"},
    {"en": "sellotape", "ru": "скотч", "part_of_speech": "n", "pronunciation": "/ˈseləteɪp/"},
    {"en": "shampoo", "ru": "шампунь", "part_of_speech": "n", "pronunciation": "/ʃæmˈpuː/"},
    {"en": "size", "ru": "размер", "part_of_speech": "n", "pronunciation": "/saɪz/"},
    {"en": "slice", "ru": "кусок", "part_of_speech": "n", "pronunciation": "/slaɪs/"},
    {"en": "smoothie", "ru": "смузи", "part_of_speech": "n", "pronunciation": "/ˈsmuːði/"},
    {"en": "some", "ru": "некоторые, одни", "part_of_speech": "det", "pronunciation": "/sʌm/"},
    {"en": "sorry", "ru": "извините", "part_of_speech": "phr", "pronunciation": "/ˈsɒri/"},
    {"en": "spaghetti", "ru": "спагетти", "part_of_speech": "n", "pronunciation": "/spəˈɡeti/"},
    {"en": "spend", "ru": "тратить", "part_of_speech": "v", "pronunciation": "/spend/"},
    {"en": "spices", "ru": "специи", "part_of_speech": "pl n", "pronunciation": "/spaɪsɪz/"},
    {"en": "sports", "ru": "спорт", "part_of_speech": "pl n", "pronunciation": "/spɔːts/"},
    {"en": "stamp", "ru": "марка", "part_of_speech": "n", "pronunciation": "/stæmp/"},
    {"en": "starving", "ru": "голодающий", "part_of_speech": "adj", "pronunciation": "/stɑːvɪŋ/"},
    {"en": "stationer’s", "ru": "канцелярия", "part_of_speech": "n", "pronunciation": "/ˈsteɪʃnəz/"},
    {"en": "steak", "ru": "стейк", "part_of_speech": "n", "pronunciation": "/steɪk/"},
    {"en": "still", "ru": "все еще", "part_of_speech": "adv", "pronunciation": "/stɪl/"},
    {"en": "strawberries", "ru": "клубника", "part_of_speech": "pl n", "pronunciation": "/ˈstrɔːbəriz/"},
    {"en": "sugar", "ru": "сахар", "part_of_speech": "n", "pronunciation": "/ˈʃʊɡə(r)/"},
    {"en": "survey", "ru": "анкета, опросник", "part_of_speech": "n", "pronunciation": "/ˈsɜːveɪ/"},
    {"en": "tap water", "ru": "водопроводная вода", "part_of_speech": "n", "pronunciation": "/ˈtæp  wɔːtə(r)/"},
    {"en": "tea", "ru": "чай", "part_of_speech": "n", "pronunciation": "/tiː/"}
]