const unit03 = [
    {"en": "always", "ru": "всегда", "part_of_speech": "adv", "pronunciation": "/ˈɔːlweɪz/"},
    {"en": "apartment", "ru": "квартира", "part_of_speech": "n", "pronunciation": "/əˈpɑːtmənt/"},
    {"en": "application form", "ru": "форма заявки", "part_of_speech": "n", "pronunciation": "/ˌæplɪˈkeɪʃn fɔːm/"},
    {"en": "badminton", "ru": "бадминтон", "part_of_speech": "n", "pronunciation": "/ˈbædmɪntən/"},
    {"en": "band", "ru": "группа (музыкаотная)", "part_of_speech": "n", "pronunciation": "/bænd/"},
    {"en": "barefoot", "ru": "босиком", "part_of_speech": "adj", "pronunciation": "/ˈbeəfʊt/"},
    {"en": "bath", "ru": "ванна", "part_of_speech": "n", "pronunciation": "/bɑːθ/"},
    {"en": "bed", "ru": "кровать", "part_of_speech": "n", "pronunciation": "/bed/"},
    {"en": "bilingual", "ru": "двуязычный", "part_of_speech": "adj", "pronunciation": "/ˌbaɪˈlɪŋɡwəl/"},
    {"en": "books", "ru": "книги", "part_of_speech": "pl n", "pronunciation": "/bʊks/"},
    {"en": "bookstore", "ru": "книжный магазин", "part_of_speech": "n", "pronunciation": "/ˈbʊkstɔː/"},
    {"en": "boutiques", "ru": "бутики", "part_of_speech": "pl n", "pronunciation": "/buːˈtiːks/"},
    {"en": "cards", "ru": "открытки", "part_of_speech": "pl n", "pronunciation": "/kɑːdz/"},
    {"en": "chicken", "ru": "курица", "part_of_speech": "n", "pronunciation": "/ˈtʃɪkɪn/"},
    {"en": "cinema", "ru": "кинотеатр", "part_of_speech": "n", "pronunciation": "/ˈsɪnəmə(r)/"},
    {"en": "computer", "ru": "компьютер", "part_of_speech": "n", "pronunciation": "/kəmˈpjuːtə(r)/"},
    {"en": "cook", "ru": "готовить", "part_of_speech": "v", "pronunciation": "/kʊk/"},
    {"en": "countryside", "ru": "сельская местность", "part_of_speech": "n", "pronunciation": "/ˈkʌntrisaɪd/"},
    {"en": "cycling", "ru": "езда на велосипеде", "part_of_speech": "n", "pronunciation": "/ˈsaɪklɪŋ/"},
    {"en": "dancing", "ru": "танцы", "part_of_speech": "n", "pronunciation": "/ˈdɑːnsɪŋ/"},
    {"en": "early", "ru": "ранний", "part_of_speech": "adj", "pronunciation": "/ˈɜːli/"},
    {"en": "enjoy", "ru": "наслаждаться", "part_of_speech": "v", "pronunciation": "/ɪnˈdʒɔɪ/"},
    {"en": "evening", "ru": "вечер", "part_of_speech": "n", "pronunciation": "/ˈiːvnɪŋ/"},
    {"en": "excuse me", "ru": "извините", "part_of_speech": "", "pronunciation": "/ɪkˈskjuːs mi/"},
    {"en": "exercise", "ru": "упражнение", "part_of_speech": "n", "pronunciation": "/ˈeksəsaɪz/"},
    {"en": "finish", "ru": "закончить", "part_of_speech": "v", "pronunciation": "/ˈfɪnɪʃ/"},
    {"en": "flowers", "ru": "цветы", "part_of_speech": "pl n", "pronunciation": "/ˈflaʊəz/"},
    {"en": "football", "ru": "футбол", "part_of_speech": "n", "pronunciation": "/ˈfʊtbɔːl/"},
    {"en": "foreign", "ru": "иностранный", "part_of_speech": "adj", "pronunciation": "/ˈfɒrən/"},
    {"en": "garden centre", "ru": "садовый центр", "part_of_speech": "n", "pronunciation": "/ˈɡɑːdn sentə(r)/"},
    {"en": "get up", "ru": "вставать", "part_of_speech": "v", "pronunciation": "/ɡet ˈʌp/"},
    {"en": "golf", "ru": "гольф", "part_of_speech": "n", "pronunciation": "/ɡɒlf/"},
    {"en": "grass", "ru": "трава", "part_of_speech": "n", "pronunciation": "/ɡrɑːs/"},
    {"en": "happy", "ru": "счастливый", "part_of_speech": "adj", "pronunciation": "/ˈhæpi/"},
    {"en": "holiday", "ru": "праздник", "part_of_speech": "n", "pronunciation": "/ˈhɒlədeɪ/"},
    {"en": "indoor", "ru": "внутри", "part_of_speech": "adj", "pronunciation": "/ˈɪndɔː(r)/"},
    {"en": "Indian", "ru": "индийский", "part_of_speech": "adj", "pronunciation": "/ˈɪndiən/"},
    {"en": "Japanese", "ru": "японский", "part_of_speech": "adj", "pronunciation": "/ˌdʒæpəˈniːz/"},
    {"en": "listen", "ru": "слушать", "part_of_speech": "v", "pronunciation": "/ˈlɪsn/"},
    {"en": "little", "ru": "маленький", "part_of_speech": "adj", "pronunciation": "/ˈlɪtl/"},
    {"en": "massage", "ru": "массаж", "part_of_speech": "n", "pronunciation": "/ˈmæsɑːʒ/"},
    {"en": "mobile phone", "ru": "мобильный телефон", "part_of_speech": "n", "pronunciation": "/ˈməʊbaɪl fəʊn/"},
    {"en": "music", "ru": "музыка", "part_of_speech": "n", "pronunciation": "/ˈmjuːzɪk/"},
    {"en": "often", "ru": "часто", "part_of_speech": "adv", "pronunciation": "/ˈɒftən/"},
    {"en": "outdoor", "ru": "на открытом воздухе, на улице", "part_of_speech": "adj", "pronunciation": "/ˈaʊtdɔː(r)/"},
    {"en": "pardon", "ru": "извините", "part_of_speech": "", "pronunciation": "/ˈpɑːdn/"},
    {"en": "personal", "ru": "личный", "part_of_speech": "adj", "pronunciation": "/ˈpɜːsənl/"},
    {"en": "poker", "ru": "покер", "part_of_speech": "n", "pronunciation": "/ˈpəʊkə(r)/"},
    {"en": "post code", "ru": "почтовый индекс", "part_of_speech": "n", "pronunciation": "/ˈpəʊst kəʊd/"},
    {"en": "postcard", "ru": "открытка", "part_of_speech": "n", "pronunciation": "/ˈpəʊstkɑːd/"},
    {"en": "problem", "ru": "проблема", "part_of_speech": "n", "pronunciation": "/ˈprɒbləm/"},
    {"en": "programme", "ru": "программа", "part_of_speech": "n", "pronunciation": "/ˈprəʊɡræm/"},
    {"en": "pub", "ru": "паб", "part_of_speech": "n", "pronunciation": "/pʌb/"},
    {"en": "pudding", "ru": "пудинг", "part_of_speech": "n", "pronunciation": "/ˈpʊdɪŋ/"},
    {"en": "restaurant", "ru": "ресторан", "part_of_speech": "n", "pronunciation": "/ˈrestrɒnt/"},
    {"en": "roast", "ru": "жареное", "part_of_speech": "n", "pronunciation": "/rəʊst/"},
    {"en": "running", "ru": "бег", "part_of_speech": "n", "pronunciation": "/ˈrʌnɪŋ/"},
    {"en": "sailing", "ru": "плавать под парусом", "part_of_speech": "n", "pronunciation": "/ˈseɪlɪŋ/"},
    {"en": "Saturday", "ru": "суббота", "part_of_speech": "n", "pronunciation": "/ˈsætədeɪ/"},
    {"en": "singer", "ru": "певец", "part_of_speech": "n", "pronunciation": "/ˈsɪŋə(r)/"},
    {"en": "skiing", "ru": "кататься на лыжах", "part_of_speech": "n", "pronunciation": "/ˈskiːɪŋ/"},
    {"en": "spa", "ru": "спа", "part_of_speech": "n", "pronunciation": "/spɑː/"},
    {"en": "squash", "ru": "сквош", "part_of_speech": "n", "pronunciation": "/skwɒʃ/"},
    {"en": "sticky", "ru": "липкий", "part_of_speech": "adj", "pronunciation": "/ˈstɪki/"},
    {"en": "Sunday", "ru": "воскресенье", "part_of_speech": "n", "pronunciation": "/ˈsʌndeɪ/"},
    {"en": "swimming", "ru": "плавание", "part_of_speech": "n", "pronunciation": "/ˈswɪmɪŋ/"},
    {"en": "takeaway", "ru": "на вынос (еда)", "part_of_speech": "n", "pronunciation": "/ˈteɪkəweɪ/"},
    {"en": "tennis", "ru": "теннис", "part_of_speech": "n", "pronunciation": "/ˈtenɪs/"},
    {"en": "Thursday", "ru": "четверг", "part_of_speech": "n", "pronunciation": "/ˈθɜːzdeɪ/"},
    {"en": "toffee", "ru": "ириска", "part_of_speech": "n", "pronunciation": "/ˈtɒfi/"},
    {"en": "traffic", "ru": "трафик", "part_of_speech": "n", "pronunciation": "/ˈtræfɪk/"},
    {"en": "Tuesday", "ru": "вторник", "part_of_speech": "n", "pronunciation": "/ˈtjuːzdeɪ/"},
    {"en": "Turkey", "ru": "Турция", "part_of_speech": "n", "pronunciation": "/ˈtɜːki/"},
    {"en": "usually", "ru": "обычно", "part_of_speech": "adv", "pronunciation": "/ˈjuʒəli/"},
    {"en": "warm", "ru": "тёплый", "part_of_speech": "adj", "pronunciation": "/wɔːm/"},
    {"en": "Wednesday", "ru": "среда", "part_of_speech": "n", "pronunciation": "/ˈwenzdeɪ/"},
    {"en": "week", "ru": "неделя", "part_of_speech": "n", "pronunciation": "/wiːk/"},
    {"en": "windsurfing", "ru": "виндсёрфинг", "part_of_speech": "n", "pronunciation": "/ˈwɪndsɜːfɪŋ/"}
]