const unit05 = [
    {"en": "advertisement", "ru": "реклама", "part_of_speech": "n", "pronunciation": "/ədˈvɜːtɪsmənt/"},
    {"en": "afford", "ru": "позволить себе", "part_of_speech": "v", "pronunciation": "/əˈfɔːd/"},
    {"en": "art", "ru": "искусство", "part_of_speech": "n", "pronunciation": "/ɑːt/"},
    {"en": "bag", "ru": "сумка", "part_of_speech": "n", "pronunciation": "/bæɡ/"},
    {"en": "bike", "ru": "велосипед", "part_of_speech": "n", "pronunciation": "/baɪk/"},
    {"en": "borrow", "ru": "отдолжить, занимать", "part_of_speech": "v", "pronunciation": "/ˈbɒrəʊ/"},
    {"en": "business", "ru": "бизнес", "part_of_speech": "n", "pronunciation": "/ˈbɪznəs/"},
    {"en": "cello", "ru": "виолончель", "part_of_speech": "n", "pronunciation": "/ˈtʃeləʊ/"},
    {"en": "certainly", "ru": "конечно", "part_of_speech": "adv", "pronunciation": "/ˈsɜːtnli/"},
    {"en": "cheese", "ru": "сыр", "part_of_speech": "n", "pronunciation": "/tʃiːz/"},
    {"en": "child", "ru": "ребенок", "part_of_speech": "n", "pronunciation": "/tʃaɪld/"},
    {"en": "Chinese", "ru": "китайский", "part_of_speech": "adj", "pronunciation": "/ˌtʃaɪˈniːz/"},
    {"en": "classical music", "ru": "классическая музыка", "part_of_speech": "n", "pronunciation": "/ˈklæsɪkl ˈmjuːzɪk/"},
    {"en": "concert", "ru": "концерт", "part_of_speech": "n", "pronunciation": "/ˈkɒnsət/"},
    {"en": "country and western", "ru": "кантри и вестерн", "part_of_speech": "n", "pronunciation": "/ˈkʌntri ənd ˈwestən/"},
    {"en": "credit card", "ru": "кредитная карта", "part_of_speech": "n", "pronunciation": "/ˈkredɪt kɑːd/"},
    {"en": "cry", "ru": "плакать", "part_of_speech": "v", "pronunciation": "/kraɪ/"},
    {"en": "drive", "ru": "вести", "part_of_speech": "v", "pronunciation": "/draɪv/"},
    {"en": "dry cleaning", "ru": "сухая уборка, химчистка", "part_of_speech": "n", "pronunciation": "/ˌdraɪ ˈkliːnɪŋ/"},
    {"en": "favour", "ru": "отдолдение, услуга", "part_of_speech": "n", "pronunciation": "/ˈfeɪvə(r)/"},
    {"en": "fly", "ru": "летать", "part_of_speech": "v", "pronunciation": "/flaɪ/"},
    {"en": "foreign language", "ru": "иностранный язык", "part_of_speech": "n", "pronunciation": "/ˈfɒrən ˈlæŋɡwɪdʒ/"},
    {"en": "glasses", "ru": "очки", "part_of_speech": "pl n", "pronunciation": "/glɑːsɪz/"},
    {"en": "guitar", "ru": "гитара", "part_of_speech": "n", "pronunciation": "/ɡɪˈtɑː(r)/"},
    {"en": "hard", "ru": "жёсткий", "part_of_speech": "adj", "pronunciation": "/hɑːd/"},
    {"en": "hard-working", "ru": "усердно работать, трудолюбивый", "part_of_speech": "adj", "pronunciation": "/ˌhɑːd ˈwɜːkɪŋ/"},
    {"en": "hero", "ru": "герой", "part_of_speech": "n", "pronunciation": "/ˈhɪərəʊ/"},
    {"en": "housewife", "ru": "домохозяйка", "part_of_speech": "n", "pronunciation": "/ˈhaʊswaɪf/"},
    {"en": "ice-cream", "ru": "мороженое", "part_of_speech": "n", "pronunciation": "/ˈaɪs kriːm/"},
    {"en": "important", "ru": "важный", "part_of_speech": "adj", "pronunciation": "/ɪmˈpɔːtnt/"},
    {"en": "independent", "ru": "независимый", "part_of_speech": "adj", "pronunciation": "/ˌɪndɪˈpendənt/"},
    {"en": "interested", "ru": "заинтересованный", "part_of_speech": "adj", "pronunciation": "/ˈɪntrestɪd/"},
    {"en": "jeans", "ru": "джинсы", "part_of_speech": "pl n", "pronunciation": "/dʒiːnz/"},
    {"en": "jump", "ru": "прыгать", "part_of_speech": "v", "pronunciation": "/dʒʌmp/"},
    {"en": "lift", "ru": "лифт", "part_of_speech": "n", "pronunciation": "/lɪft/"},
    {"en": "light", "ru": "свет", "part_of_speech": "n", "pronunciation": "/laɪt/"},
    {"en": "look after", "ru": "заботиться о", "part_of_speech": "v", "pronunciation": "/lʊk ˈɑːftə(r)/"},
    {"en": "menu", "ru": "меню", "part_of_speech": "n", "pronunciation": "/ˈmenjuː/"},
    {"en": "metre", "ru": "метр", "part_of_speech": "n", "pronunciation": "/ˈmiːtə(r)/"},
    {"en": "Mexican", "ru": "мексиканец", "part_of_speech": "n", "pronunciation": "/ˈmeksɪkən/"},
    {"en": "moment", "ru": "момент", "part_of_speech": "n", "pronunciation": "/ˈməʊmənt/"},
    {"en": "motorbike", "ru": "мотоцикл", "part_of_speech": "n", "pronunciation": "/ˈməʊtəbaɪk/"},
    {"en": "musical instrument", "ru": "музыкальный инструмент", "part_of_speech": "n", "pronunciation": "/ˌmjuːzɪkl ˈinstrəmənt/"},
    {"en": "occasion", "ru": "случай", "part_of_speech": "n", "pronunciation": "/əˈkeɪʒn/"},
    {"en": "open", "ru": "открывать", "part_of_speech": "v", "pronunciation": "/ˈəʊpən/"},
    {"en": "painter", "ru": "художник", "part_of_speech": "n", "pronunciation": "/ˈpeɪntə(r)/"},
    {"en": "painting", "ru": "картина", "part_of_speech": "n", "pronunciation": "/ˈpeɪntɪŋ/"},
    {"en": "passionate", "ru": "страстный", "part_of_speech": "adj", "pronunciation": "/ˈpæʃənət/"},
    {"en": "pay", "ru": "платить", "part_of_speech": "v", "pronunciation": "/peɪ/"},
    {"en": "petrol", "ru": "бензин", "part_of_speech": "n", "pronunciation": "/ˈpetrəl/"},
    {"en": "pianist", "ru": "пианист", "part_of_speech": "n", "pronunciation": "/ˈpɪənɪst/"},
    {"en": "post", "ru": "отправлять почту", "part_of_speech": "v", "pronunciation": "/pəʊst/"},
    {"en": "prodigy", "ru": "гений", "part_of_speech": "adv", "pronunciation": "/prəˈfeʃənəli/"},
    {"en": "proud", "ru": "гордый", "part_of_speech": "adj", "pronunciation": "/praʊd/"},
    {"en": "resort", "ru": "курорт", "part_of_speech": "n", "pronunciation": "/rɪˈzɔːt/"},
    {"en": "return", "ru": "возвращаться", "part_of_speech": "v", "pronunciation": "/rɪˈtɜːn/"},
    {"en": "rich", "ru": "богатый", "part_of_speech": "adj", "pronunciation": "/rɪtʃ/"},
    {"en": "ride", "ru": "ездить верхом", "part_of_speech": "v", "pronunciation": "/raɪd/"},
    {"en": "sandwich", "ru": "бутерброд", "part_of_speech": "n", "pronunciation": "/ˈsænwɪdʒ/"},
    {"en": "see", "ru": "видеть", "part_of_speech": "v", "pronunciation": "/siː/"},
    {"en": "send", "ru": "отправлять", "part_of_speech": "v", "pronunciation": "/send/"},
    {"en": "sentimental", "ru": "сентиментальный", "part_of_speech": "adj", "pronunciation": "/ˌsentɪˈmentl/"},
    {"en": "shop", "ru": "магазин", "part_of_speech": "n", "pronunciation": "/ʃɒp/"},
    {"en": "sit", "ru": "сидеть", "part_of_speech": "v", "pronunciation": "/sɪt/"},
    {"en": "skateboard", "ru": "скейтборд", "part_of_speech": "v", "pronunciation": "/ˈskeɪtbɔːd/"},
    {"en": "speed", "ru": "скорость", "part_of_speech": "n", "pronunciation": "/spiːd/"},
    {"en": "station", "ru": "станция", "part_of_speech": "n", "pronunciation": "/ˈsteɪʃn/"},
    {"en": "stop", "ru": "остановить", "part_of_speech": "v", "pronunciation": "/stɒp/"},
    {"en": "succeed", "ru": "преуспивать, добиться успеха", "part_of_speech": "v", "pronunciation": "/səkˈsiːd/"},
    {"en": "success", "ru": "успех", "part_of_speech": "n", "pronunciation": "/səkˈses/"},
    {"en": "suit", "ru": "костюм", "part_of_speech": "n", "pronunciation": "/suːt/"},
    {"en": "sun", "ru": "солнце", "part_of_speech": "n", "pronunciation": "/sʌn/"},
    {"en": "talented", "ru": "одарённый", "part_of_speech": "adj", "pronunciation": "/ˈtæləntɪd/"},
    {"en": "talk", "ru": "говорить", "part_of_speech": "v", "pronunciation": "/tɔːk/"},
    {"en": "television", "ru": "телевидение", "part_of_speech": "n", "pronunciation": "/ˈtelɪvɪʒn/"},
    {"en": "text message", "ru": "текстовое сообщение", "part_of_speech": "n", "pronunciation": "/tekst ˈmesɪdʒ/"},
    {"en": "ticket", "ru": "билет", "part_of_speech": "n", "pronunciation": "/ˈtɪkɪt/"},
    {"en": "tie", "ru": "галстук", "part_of_speech": "n", "pronunciation": "/taɪ/"},
    {"en": "turn back", "ru": "повернуть назад", "part_of_speech": "v", "pronunciation": "/tɜːn ˈbæk/"},
    {"en": "violin", "ru": "скрипка", "part_of_speech": "n", "pronunciation": "/ˌvaɪəˈlɪn/"},
    {"en": "violinist", "ru": "скрипач", "part_of_speech": "n", "pronunciation": "/ˌvaɪəˈlɪnɪst/"},
    {"en": "water", "ru": "вода", "part_of_speech": "n", "pronunciation": "/ˈwɔːtə(r)/"},
    {"en": "wear", "ru": "носить", "part_of_speech": "v", "pronunciation": "/weə(r)/"}
]