const unit10 = [
    {"en": "actor", "ru": "актер", "part_of_speech": "n", "pronunciation": "/ˈæktə(r)/"},
    {"en": "affect", "ru": "влиять, повлиять", "part_of_speech": "v", "pronunciation": "/əˈfekt/"},
    {"en": "alike", "ru": "похожий", "part_of_speech": "adj", "pronunciation": "/əˈlaɪk/"},
    {"en": "attached", "ru": "прикрепленный", "part_of_speech": "adj", "pronunciation": "/əˈtætʃt/"},
    {"en": "bank holiday", "ru": "выходной", "part_of_speech": "n", "pronunciation": "/ˌbæŋk  ˈhɒlədeɪ/"},
    {"en": "below", "ru": "ниже", "part_of_speech": "prep", "pronunciation": "/bɪˈləʊ/"},
    {"en": "blond", "ru": "светловолосый", "part_of_speech": "adj", "pronunciation": "/blɒnd/"},
    {"en": "blue", "ru": "синий", "part_of_speech": "n", "pronunciation": "/bluː/"},
    {"en": "bone", "ru": "кость", "part_of_speech": "n", "pronunciation": "/bəʊn/"},
    {"en": "boots", "ru": "сапоги", "part_of_speech": "pl n", "pronunciation": "/buːts/"},
    {"en": "brown", "ru": "коричневый", "part_of_speech": "n", "pronunciation": "/braʊn/"},
    {"en": "build", "ru": "строить", "part_of_speech": "v", "pronunciation": "/bɪld/"},
    {"en": "coat", "ru": "пальто", "part_of_speech": "n", "pronunciation": "/kəʊt/"},
    {"en": "compartment", "ru": "отсек, камера", "part_of_speech": "n", "pronunciation": "/kəmˈpɑːtmənt/"},
    {"en": "compete", "ru": "соревноваться", "part_of_speech": "v", "pronunciation": "/kəmˈpiːt/"},
    {"en": "conditions", "ru": "условия", "part_of_speech": "pl n", "pronunciation": "/kənˈdɪʃnz/"},
    {"en": "couple", "ru": "пара", "part_of_speech": "n", "pronunciation": "/ˈkʌpl/"},
    {"en": "dark", "ru": "темный", "part_of_speech": "adj", "pronunciation": "/dɑːk/"},
    {"en": "decide", "ru": "решать", "part_of_speech": "v", "pronunciation": "/dɪˈsaɪd/"},
    {"en": "detective", "ru": "детектив", "part_of_speech": "n", "pronunciation": "/dɪˈtektɪv/"},
    {"en": "develop", "ru": "развивать", "part_of_speech": "v", "pronunciation": "/dɪˈveləp/"},
    {"en": "dress", "ru": "платье", "part_of_speech": "n", "pronunciation": "/dres/"},
    {"en": "earth", "ru": "Земля", "part_of_speech": "n", "pronunciation": "/ɜːθ/"},
    {"en": "effects", "ru": "эффекты", "part_of_speech": "pl n", "pronunciation": "/ɪˈfekts/"},
    {"en": "experiment", "ru": "эксперимент", "part_of_speech": "n", "pronunciation": "/ɪkˈsperɪmənt/"},
    {"en": "fair", "ru": "справедливый", "part_of_speech": "adj", "pronunciation": "/feə/"},
    {"en": "fight", "ru": "драться", "part_of_speech": "v", "pronunciation": "/faɪt/"},
    {"en": "float", "ru": "плавать (на лодке/корабле)", "part_of_speech": "v", "pronunciation": "/fləʊt/"},
    {"en": "glasses", "ru": "очки", "part_of_speech": "pl n", "pronunciation": "/ˈglɑːsɪz/"},
    {"en": "good-looking", "ru": "хорошо выглядит, привлекательный", "part_of_speech": "adj", "pronunciation": "/ˌɡʊd  ˈlʊkɪŋ/"},
    {"en": "gravity", "ru": "гравитация", "part_of_speech": "n", "pronunciation": "/ˈɡrævəti/"},
    {"en": "handsome", "ru": "симпатичный, красивый (муж.р.)", "part_of_speech": "adj", "pronunciation": "/ˈhænsəm/"},
    {"en": "happen", "ru": "случаться", "part_of_speech": "v", "pronunciation": "/ˈhæpən/"},
    {"en": "hat", "ru": "шляпа", "part_of_speech": "n", "pronunciation": "/hæt/"},
    {"en": "identical", "ru": "идентичный", "part_of_speech": "adj", "pronunciation": "/aɪˈdentɪkl/"},
    {"en": "incredible", "ru": "невероятный", "part_of_speech": "adj", "pronunciation": "/ɪnˈkredəbl/"},
    {"en": "instruments", "ru": "инструменты", "part_of_speech": "pl n", "pronunciation": "/ˈɪnstrəmənts/"},
    {"en": "jeans", "ru": "джинсы", "part_of_speech": "n", "pronunciation": "/dʒiːnz/"},
    {"en": "laboratory", "ru": "лаборатория", "part_of_speech": "n", "pronunciation": "/ləˈbɒrətri/"},
    {"en": "laptop", "ru": "ноутбук", "part_of_speech": "n", "pronunciation": "/ˈlæptɒp/"},
    {"en": "long", "ru": "длинный", "part_of_speech": "adj", "pronunciation": "/lɒŋ/"},
    {"en": "message", "ru": "сообщение", "part_of_speech": "n", "pronunciation": "/ˈmesɪdʒ/"},
    {"en": "muscle", "ru": "мышца", "part_of_speech": "n", "pronunciation": "/ˈmʌsl/"},
    {"en": "never mind", "ru": "не важно", "part_of_speech": "phrase", "pronunciation": "/ˈnevə(r)  maɪnd/"},
    {"en": "noise", "ru": "шум", "part_of_speech": "n", "pronunciation": "/nɔɪz/"},
    {"en": "orbit", "ru": "орбита", "part_of_speech": "v", "pronunciation": "/ˈɔːbɪt/"},
    {"en": "origin", "ru": "происхождение", "part_of_speech": "n", "pronunciation": "/ˈɒrɪdʒɪn/"},
    {"en": "oxygen", "ru": "кислород", "part_of_speech": "n", "pronunciation": "/ˈɒksɪdʒən/"},
    {"en": "planet", "ru": "планета", "part_of_speech": "n", "pronunciation": "/ˈplænɪt/"},
    {"en": "preparation", "ru": "подготовка", "part_of_speech": "n", "pronunciation": "/ˌprepəˈreɪʃn/"},
    {"en": "pretty", "ru": "милый, симпатичный (жен.р.)", "part_of_speech": "adj", "pronunciation": "/ˈprɪti/"},
    {"en": "purple", "ru": "фиолетовый", "part_of_speech": "n", "pronunciation": "/ˈpɜːpl/"},
    {"en": "research", "ru": "изучение, исследование", "part_of_speech": "n", "pronunciation": "/ˈriːsɜːtʃ/"},
    {"en": "romance", "ru": "романтика", "part_of_speech": "n", "pronunciation": "/ˈrəʊmæns/"},
    {"en": "sauce", "ru": "соус", "part_of_speech": "n", "pronunciation": "/sɔːs/"},
    {"en": "scarf", "ru": "шарф", "part_of_speech": "n", "pronunciation": "/skɑːf/"},
    {"en": "shoes", "ru": "обувь", "part_of_speech": "pl n", "pronunciation": "/ʃuːz/"},
    {"en": "short", "ru": "короткий", "part_of_speech": "adj", "pronunciation": "/ʃɔːt/"},
    {"en": "shorts", "ru": "шорты", "part_of_speech": "pl n", "pronunciation": "/ʃɔːts/"},
    {"en": "skirt", "ru": "юбка", "part_of_speech": "n", "pronunciation": "/skɜːt/"},
    {"en": "spicy", "ru": "острый", "part_of_speech": "adj", "pronunciation": "/ˈspaɪsi/"},
    {"en": "spoon", "ru": "ложка", "part_of_speech": "n", "pronunciation": "/spuːn/"},
    {"en": "star", "ru": "звезда", "part_of_speech": "n", "pronunciation": "/stɑː(r)/"},
    {"en": "suit", "ru": "костюм", "part_of_speech": "n", "pronunciation": "/suːt/"},
    {"en": "supplies", "ru": "припасы", "part_of_speech": "pl n", "pronunciation": "/səˈplaɪz/"},
    {"en": "switch on", "ru": "включить", "part_of_speech": "v", "pronunciation": "/swɪtʃ  ˈɒn/"},
    {"en": "T-shirt", "ru": "футболка", "part_of_speech": "n", "pronunciation": "/ˈtiː ʃɜːt/"},
    {"en": "tall", "ru": "высокий", "part_of_speech": "adj", "pronunciation": "/tɔːl/"},
    {"en": "tasty", "ru": "вкусный", "part_of_speech": "adj", "pronunciation": "/ˈteɪsti/"},
    {"en": "tin", "ru": "олово", "part_of_speech": "n", "pronunciation": "/tɪn/"},
    {"en": "trainers", "ru": "кроссовки", "part_of_speech": "pl n", "pronunciation": "/ˈtreɪnəz/"},
    {"en": "truth", "ru": "правда, истина", "part_of_speech": "n", "pronunciation": "/truːθ/"},
    {"en": "twins", "ru": "близнецы", "part_of_speech": "pl n", "pronunciation": "/twɪnz/"},
    {"en": "universe", "ru": "вселенная", "part_of_speech": "n", "pronunciation": "/ˈjuːnɪvɜːs/"},
    {"en": "unusual", "ru": "необычный", "part_of_speech": "adj", "pronunciation": "/ʌnˈjuːʒuəl/"},
    {"en": "washing-up", "ru": "мытье посуды", "part_of_speech": "n", "pronunciation": "/ˌwɒʃɪŋ  ˈʌp/"}
]